package tes.common.database;

import com.google.common.base.CaseFormat;
import cpw.mods.fml.common.registry.GameRegistry;
import tes.common.block.TESItemBlockWeaponRack;
import tes.common.block.TESItemPlantableBlock;
import tes.common.block.brick.*;
import tes.common.block.leaves.*;
import tes.common.block.other.*;
import tes.common.block.pillar.TESBlockPillar1;
import tes.common.block.pillar.TESBlockPillar2;
import tes.common.block.planks.*;
import tes.common.block.sapling.*;
import tes.common.block.slab.*;
import tes.common.block.table.*;
import tes.common.block.wall.*;
import tes.common.block.wbeam.*;
import tes.common.block.wood.*;
import tes.common.block.wslab.*;
import tes.common.item.other.*;
import tes.common.item.weapon.TESItemBomb;
import tes.common.tileentity.TESTileEntitySignCarved;
import tes.common.tileentity.TESTileEntitySignCarvedValyrian;
import tes.common.util.TESEnumDyeColor;
import net.minecraft.block.Block;
import net.minecraft.block.BlockPressurePlate;
import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.init.Blocks;
import net.minecraft.item.ItemBlock;
import net.minecraft.item.ItemLeaves;

import java.util.ArrayList;
import java.util.Collection;
import java.util.EnumMap;
import java.util.Map;

@SuppressWarnings({"WeakerAccess", "PublicField"})
public class TESBlocks {
	public static final Collection<Block> CONTENT = new ArrayList<>();

	public static final Map<TESEnumDyeColor, TESBlockConcretePowder> CONCRETE_POWDER = new EnumMap<>(TESEnumDyeColor.class);
	public static final Map<TESEnumDyeColor, TESBlockConcrete> CONCRETE = new EnumMap<>(TESEnumDyeColor.class);

	public static Block aleHorn;
	public static Block aleHornGold;
	public static Block alloyForge;
	public static Block appleCrumble;
	public static Block aridGrass;
	public static Block armorStand;
	public static Block asshaiBars;
	public static Block asshaiDirt;
	public static Block asshaiFlower;
	public static Block asshaiGrass;
	public static Block asshaiMoss;
	public static Block asshaiThorn;
	public static Block asshaiTorch;
	public static Block banana;
	public static Block bananaCake;
	public static Block bank;
	public static Block barrel;
	public static Block barrier;
	public static Block basaltGravel;
	public static Block beacon;
	public static Block berryBush;
	public static Block berryPie;
	public static Block birdCage;
	public static Block birdCageWood;
	public static Block blackroot;
	public static Block blockGem;
	public static Block blockMetal1;
	public static Block blockMetal2;
	public static Block bluebell;
	public static Block bomb;
	public static Block boneBlock;
	public static Block bookshelfStorage;
	public static Block brick1;
	public static Block brick2;
	public static Block brick3;
	public static Block brick4;
	public static Block brick5;
	public static Block brick6;
	public static Block brickIce;
	public static Block bronzeBars;
	public static Block butterflyJar;
	public static Block buttonAndesite;
	public static Block buttonBasalt;
	public static Block buttonChalk;
	public static Block buttonDiorite;
	public static Block buttonGranite;
	public static Block buttonLabradorite;
	public static Block buttonRhyolite;
	public static Block ceramicMug;
	public static Block ceramicPlate;
	public static Block chain;
	public static Block chandelier;
	public static Block cherryPie;
	public static Block chestBasket;
	public static Block chestSandstone;
	public static Block chestStone;
	public static Block clayTile;
	public static Block clayTileDyed;
	public static Block clover;
	public static Block cobblebrick;
	public static Block commandTable;
	public static Block coralReef;
	public static Block cornStalk;
	public static Block date;
	public static Block daub;
	public static Block deadMarshPlant;
	public static Block dirtPath;
	public static Block doorAcacia;
	public static Block doorAlmond;
	public static Block doorApple;
	public static Block doorAramant;
	public static Block doorAspen;
	public static Block doorBanana;
	public static Block doorBaobab;
	public static Block doorBeech;
	public static Block doorBirch;
	public static Block doorCatalpa;
	public static Block doorCedar;
	public static Block doorCharred;
	public static Block doorCherry;
	public static Block doorChestnut;
	public static Block doorCypress;
	public static Block doorDarkOak;
	public static Block doorDatePalm;
	public static Block doorDragon;
	public static Block doorFir;
	public static Block doorFotinia;
	public static Block doorGreenOak;
	public static Block doorHolly;
	public static Block doorIbbinia;
	public static Block doorJungle;
	public static Block doorKanuka;
	public static Block doorLarch;
	public static Block doorLemon;
	public static Block doorLime;
	public static Block doorMahogany;
	public static Block doorMango;
	public static Block doorMangrove;
	public static Block doorMaple;
	public static Block doorOlive;
	public static Block doorOrange;
	public static Block doorPalm;
	public static Block doorPear;
	public static Block doorPine;
	public static Block doorPlum;
	public static Block doorPomegranate;
	public static Block doorRedwood;
	public static Block doorRotten;
	public static Block doorSpruce;
	public static Block doorUlthos;
	public static Block doorWeirwood;
	public static Block doorWillow;
	public static Block doubleFlower;
	public static Block driedReeds;
	public static Block essosFlower;
	public static Block fallenLeaves1;
	public static Block fallenLeaves2;
	public static Block fallenLeaves3;
	public static Block fallenLeaves4;
	public static Block fence2;
	public static Block fence3;
	public static Block fence;
	public static Block fenceGateAcacia;
	public static Block fenceGateAlmond;
	public static Block fenceGateApple;
	public static Block fenceGateAramant;
	public static Block fenceGateAspen;
	public static Block fenceGateBanana;
	public static Block fenceGateBaobab;
	public static Block fenceGateBeech;
	public static Block fenceGateBirch;
	public static Block fenceGateCatalpa;
	public static Block fenceGateCedar;
	public static Block fenceGateCharred;
	public static Block fenceGateCherry;
	public static Block fenceGateChestnut;
	public static Block fenceGateCypress;
	public static Block fenceGateDarkOak;
	public static Block fenceGateDatePalm;
	public static Block fenceGateDragon;
	public static Block fenceGateFir;
	public static Block fenceGateFotinia;
	public static Block fenceGateGreenOak;
	public static Block fenceGateHolly;
	public static Block fenceGateIbbinia;
	public static Block fenceGateJungle;
	public static Block fenceGateKanuka;
	public static Block fenceGateLarch;
	public static Block fenceGateLemon;
	public static Block fenceGateLime;
	public static Block fenceGateMahogany;
	public static Block fenceGateMango;
	public static Block fenceGateMangrove;
	public static Block fenceGateMaple;
	public static Block fenceGateOlive;
	public static Block fenceGateOrange;
	public static Block fenceGatePalm;
	public static Block fenceGatePear;
	public static Block fenceGatePine;
	public static Block fenceGatePlum;
	public static Block fenceGatePomegranate;
	public static Block fenceGateRedwood;
	public static Block fenceGateRotten;
	public static Block fenceGateSpruce;
	public static Block fenceGateUlthos;
	public static Block fenceGateWeirwood;
	public static Block fenceGateWillow;
	public static Block fenceRotten;
	public static Block flaxCrop;
	public static Block flaxPlant;
	public static Block flowerPot;
	public static Block fruitLeaves;
	public static Block fruitSapling;
	public static Block fruitWood;
	public static Block furBed;
	public static Block fuse;
	public static Block gateBronzeBars;
	public static Block gateEssos;
	public static Block gateGold;
	public static Block gateIbben;
	public static Block gateIronBars;
	public static Block gateSilver;
	public static Block gateSothoryos;
	public static Block gateValyrian;
	public static Block gateWesteros;
	public static Block gateWooden;
	public static Block gateWoodenCross;
	public static Block gateYiTi;
	public static Block glass;
	public static Block glassBottle;
	public static Block glassPane;
	public static Block gobletCopper;
	public static Block gobletGold;
	public static Block gobletSilver;
	public static Block gobletWood;
	public static Block goldBars;
	public static Block grapevine;
	public static Block grapevineRed;
	public static Block grapevineWhite;
	public static Block hearth;
	public static Block kebabBlock;
	public static Block kebabStand;
	public static Block kebabStandSand;
	public static Block kelp;
	public static Block leaves1;
	public static Block leaves2;
	public static Block leaves3;
	public static Block leaves4;
	public static Block leaves5;
	public static Block leaves6;
	public static Block leaves7;
	public static Block leaves8;
	public static Block leaves9;
	public static Block leekCrop;
	public static Block lemonCake;
	public static Block lettuceCrop;
	public static Block lionBed;
	public static Block marigold;
	public static Block marshLights;
	public static Block marzipanBlock;
	public static Block millstone;
	public static Block mirkVines;
	public static Block mud;
	public static Block mudFarmland;
	public static Block mudGrass;
	public static Block mug;
	public static Block obsidianGravel;
	public static Block oreCobalt;
	public static Block oreCopper;
	public static Block oreGem;
	public static Block oreGlowstone;
	public static Block oreSalt;
	public static Block oreSaltpeter;
	public static Block oreSilver;
	public static Block oreSulfur;
	public static Block oreTin;
	public static Block oreValyrian;
	public static Block oven;
	public static Block pastry;
	public static Block pillar1;
	public static Block pillar2;
	public static Block pipeweedCrop;
	public static Block pipeweedPlant;
	public static Block planks1;
	public static Block planks2;
	public static Block planks3;
	public static Block planksRotten;
	public static Block plantain;
	public static Block plate;
	public static Block pressurePlateAndesite;
	public static Block pressurePlateBasalt;
	public static Block pressurePlateChalk;
	public static Block pressurePlateDiorite;
	public static Block pressurePlateGranite;
	public static Block pressurePlateLabradorite;
	public static Block pressurePlateRhyolite;
	public static Block quagmire;
	public static Block quicksand;
	public static Block redBrick;
	public static Block redClay;
	public static Block redSandstone;
	public static Block reedBars;
	public static Block reeds;
	public static Block rock;
	public static Block rope;
	public static Block rottenLog;
	public static Block rottenSlabDouble;
	public static Block rottenSlabSingle;
	public static Block sapling1;
	public static Block sapling2;
	public static Block sapling3;
	public static Block sapling4;
	public static Block sapling5;
	public static Block sapling6;
	public static Block sapling7;
	public static Block sapling8;
	public static Block sapling9;
	public static Block sarbacaneTrap;
	public static Block sarbacaneTrapGold;
	public static Block sarbacaneTrapObsidian;
	public static Block scorchedSlabDouble;
	public static Block scorchedSlabSingle;
	public static Block scorchedStone;
	public static Block scorchedWall;
	public static Block signCarved;
	public static Block signCarvedGlowing;
	public static Block silverBars;
	public static Block skullCup;
	public static Block slabBoneDouble;
	public static Block slabBoneSingle;
	public static Block slabClayTileDouble;
	public static Block slabClayTileDyedDouble1;
	public static Block slabClayTileDyedDouble2;
	public static Block slabClayTileDyedSingle1;
	public static Block slabClayTileDyedSingle2;
	public static Block slabClayTileSingle;
	public static Block slabDouble10;
	public static Block slabDouble11;
	public static Block slabDouble12;
	public static Block slabDouble1;
	public static Block slabDouble2;
	public static Block slabDouble3;
	public static Block slabDouble4;
	public static Block slabDouble5;
	public static Block slabDouble6;
	public static Block slabDouble7;
	public static Block slabDouble8;
	public static Block slabDouble9;
	public static Block slabDoubleDirt;
	public static Block slabDoubleGravel;
	public static Block slabDoubleSand;
	public static Block slabDoubleThatch;
	public static Block slabDoubleV;
	public static Block slabSingle10;
	public static Block slabSingle11;
	public static Block slabSingle12;
	public static Block slabSingle1;
	public static Block slabSingle2;
	public static Block slabSingle3;
	public static Block slabSingle4;
	public static Block slabSingle5;
	public static Block slabSingle6;
	public static Block slabSingle7;
	public static Block slabSingle8;
	public static Block slabSingle9;
	public static Block slabSingleDirt;
	public static Block slabSingleGravel;
	public static Block slabSingleSand;
	public static Block slabSingleThatch;
	public static Block slabSingleV;
	public static Block smoothStone;
	public static Block smoothStoneV;
	public static Block sothoryosDoubleTorch;
	public static Block spawnerChest;
	public static Block spawnerChestAncientEssos;
	public static Block spawnerChestStone;
	public static Block stainedGlass;
	public static Block stainedGlassPane;
	public static Block stairsAlmond;
	public static Block stairsAndesite;
	public static Block stairsAndesiteBrick;
	public static Block stairsAndesiteBrickCracked;
	public static Block stairsAndesiteBrickMossy;
	public static Block stairsApple;
	public static Block stairsAramant;
	public static Block stairsAspen;
	public static Block stairsBanana;
	public static Block stairsBaobab;
	public static Block stairsBasalt;
	public static Block stairsBasaltBrick;
	public static Block stairsBasaltBrickCracked;
	public static Block stairsBasaltWesterosBrick;
	public static Block stairsBeech;
	public static Block stairsBone;
	public static Block stairsBrickCracked;
	public static Block stairsBrickMossy;
	public static Block stairsCatalpa;
	public static Block stairsCedar;
	public static Block stairsChalk;
	public static Block stairsChalkBrick;
	public static Block stairsCharred;
	public static Block stairsCherry;
	public static Block stairsChestnut;
	public static Block stairsClayTile;
	public static Block stairsClayTileDyedBlack;
	public static Block stairsClayTileDyedBlue;
	public static Block stairsClayTileDyedBrown;
	public static Block stairsClayTileDyedCyan;
	public static Block stairsClayTileDyedGray;
	public static Block stairsClayTileDyedGreen;
	public static Block stairsClayTileDyedLightBlue;
	public static Block stairsClayTileDyedLightGray;
	public static Block stairsClayTileDyedLime;
	public static Block stairsClayTileDyedMagenta;
	public static Block stairsClayTileDyedOrange;
	public static Block stairsClayTileDyedPink;
	public static Block stairsClayTileDyedPurple;
	public static Block stairsClayTileDyedRed;
	public static Block stairsClayTileDyedWhite;
	public static Block stairsClayTileDyedYellow;
	public static Block stairsCobblestoneMossy;
	public static Block stairsCypress;
	public static Block stairsDatePalm;
	public static Block stairsDiorite;
	public static Block stairsDioriteBrick;
	public static Block stairsDragon;
	public static Block stairsFir;
	public static Block stairsFotinia;
	public static Block stairsGranite;
	public static Block stairsGraniteBrick;
	public static Block stairsGreenOak;
	public static Block stairsHolly;
	public static Block stairsIbbinia;
	public static Block stairsKanuka;
	public static Block stairsLabradorite;
	public static Block stairsLabradoriteBrick;
	public static Block stairsLabradoriteBrickCracked;
	public static Block stairsLabradoriteBrickMossy;
	public static Block stairsLarch;
	public static Block stairsLemon;
	public static Block stairsLhazarBrick;
	public static Block stairsLime;
	public static Block stairsMahogany;
	public static Block stairsMango;
	public static Block stairsMangrove;
	public static Block stairsMaple;
	public static Block stairsMudBrick;
	public static Block stairsOlive;
	public static Block stairsOrange;
	public static Block stairsPalm;
	public static Block stairsPear;
	public static Block stairsPine;
	public static Block stairsPlum;
	public static Block stairsPomegranate;
	public static Block stairsRedSandstone;
	public static Block stairsRedwood;
	public static Block stairsReed;
	public static Block stairsRhyolite;
	public static Block stairsRhyoliteBrick;
	public static Block stairsRotten;
	public static Block stairsSandstoneBrick;
	public static Block stairsSandstoneBrickCracked;
	public static Block stairsSandstoneBrickRed;
	public static Block stairsSandstoneBrickRedCracked;
	public static Block stairsScorchedStone;
	public static Block stairsSothoryosBrick;
	public static Block stairsSothoryosBrickCracked;
	public static Block stairsSothoryosBrickGold;
	public static Block stairsSothoryosBrickMossy;
	public static Block stairsSothoryosBrickObsidian;
	public static Block stairsStone;
	public static Block stairsStoneBrickCracked;
	public static Block stairsStoneBrickMossy;
	public static Block stairsThatch;
	public static Block stairsUlthos;
	public static Block stairsWeirwood;
	public static Block stairsWhiteSandstone;
	public static Block stairsWillow;
	public static Block stairsYiTiBrick;
	public static Block stairsYiTiBrickCracked;
	public static Block stairsYiTiBrickFlowers;
	public static Block stairsYiTiBrickMossy;
	public static Block stairsYiTiBrickRed;
	public static Block stalactite;
	public static Block stalactiteIce;
	public static Block stalactiteObsidian;
	public static Block strawBed;
	public static Block tableArryn;
	public static Block tableAsshai;
	public static Block tableBraavos;
	public static Block tableCrownlands;
	public static Block tableDorne;
	public static Block tableDothraki;
	public static Block tableDragonstone;
	public static Block tableGhiscar;
	public static Block tableGift;
	public static Block tableHillTribes;
	public static Block tableIbben;
	public static Block tableIronborn;
	public static Block tableJogos;
	public static Block tableLhazar;
	public static Block tableLorath;
	public static Block tableLys;
	public static Block tableMossovy;
	public static Block tableMyr;
	public static Block tableNorth;
	public static Block tableNorvos;
	public static Block tablePentos;
	public static Block tableQarth;
	public static Block tableQohor;
	public static Block tableReach;
	public static Block tableRiverlands;
	public static Block tableSothoryos;
	public static Block tableStormlands;
	public static Block tableSummer;
	public static Block tableTyrosh;
	public static Block tableVolantis;
	public static Block tableWesterlands;
	public static Block tableWildling;
	public static Block tableYiTi;
	public static Block tallGrass;
	public static Block termiteMound;
	public static Block thatch;
	public static Block thatchFloor;
	public static Block trapdoorAcacia;
	public static Block trapdoorAlmond;
	public static Block trapdoorApple;
	public static Block trapdoorAramant;
	public static Block trapdoorAspen;
	public static Block trapdoorBanana;
	public static Block trapdoorBaobab;
	public static Block trapdoorBeech;
	public static Block trapdoorBirch;
	public static Block trapdoorCatalpa;
	public static Block trapdoorCedar;
	public static Block trapdoorCharred;
	public static Block trapdoorCherry;
	public static Block trapdoorChestnut;
	public static Block trapdoorCypress;
	public static Block trapdoorDarkOak;
	public static Block trapdoorDatePalm;
	public static Block trapdoorDragon;
	public static Block trapdoorFir;
	public static Block trapdoorFotinia;
	public static Block trapdoorGreenOak;
	public static Block trapdoorHolly;
	public static Block trapdoorIbbinia;
	public static Block trapdoorJungle;
	public static Block trapdoorKanuka;
	public static Block trapdoorLarch;
	public static Block trapdoorLemon;
	public static Block trapdoorLime;
	public static Block trapdoorMahogany;
	public static Block trapdoorMango;
	public static Block trapdoorMangrove;
	public static Block trapdoorMaple;
	public static Block trapdoorOlive;
	public static Block trapdoorOrange;
	public static Block trapdoorPalm;
	public static Block trapdoorPear;
	public static Block trapdoorPine;
	public static Block trapdoorPlum;
	public static Block trapdoorPomegranate;
	public static Block trapdoorRedwood;
	public static Block trapdoorRotten;
	public static Block trapdoorSpruce;
	public static Block trapdoorUlthos;
	public static Block trapdoorWeirwood;
	public static Block trapdoorWillow;
	public static Block treasureCopper;
	public static Block treasureGold;
	public static Block treasureSilver;
	public static Block turnipCrop;
	public static Block unsmeltery;
	public static Block valyrianBars;
	public static Block wallBone;
	public static Block wallClayTile;
	public static Block wallClayTileDyed;
	public static Block wallStone1;
	public static Block wallStone2;
	public static Block wallStone3;
	public static Block wallStone4;
	public static Block wallStoneV;
	public static Block wasteBlock;
	public static Block weaponRack;
	public static Block whiteSand;
	public static Block whiteSandstone;
	public static Block wildFire;
	public static Block wildFireJar;
	public static Block willowVines;
	public static Block wineGlass;
	public static Block wood1;
	public static Block wood2;
	public static Block wood3;
	public static Block wood4;
	public static Block wood5;
	public static Block wood6;
	public static Block wood7;
	public static Block wood8;
	public static Block wood9;
	public static Block woodBeam1;
	public static Block woodBeam2;
	public static Block woodBeam3;
	public static Block woodBeam4;
	public static Block woodBeam5;
	public static Block woodBeam6;
	public static Block woodBeam7;
	public static Block woodBeam8;
	public static Block woodBeam9;
	public static Block woodBeamFruit;
	public static Block woodBeamRotten;
	public static Block woodBeamV1;
	public static Block woodBeamV2;
	public static Block woodPlate;
	public static Block woodSlabDouble1;
	public static Block woodSlabDouble2;
	public static Block woodSlabDouble3;
	public static Block woodSlabDouble4;
	public static Block woodSlabDouble5;
	public static Block woodSlabSingle1;
	public static Block woodSlabSingle2;
	public static Block woodSlabSingle3;
	public static Block woodSlabSingle4;
	public static Block woodSlabSingle5;
	public static Block yamCrop;
	public static Block yitiFlower;
	
	public static Block tableEmpire;
	
	public static Block oreOrichalcum;

	private TESBlocks() {
	}

	private static void assignContent() {
		planks1 = new TESBlockPlanks1();
		planks2 = new TESBlockPlanks2();
		planks3 = new TESBlockPlanks3();
		planksRotten = new TESBlockPlanksRotten();
		thatch = new TESBlockThatch();
		whiteSandstone = new TESBlockSandstone();

		aleHorn = new TESBlockAleHorn();
		aleHornGold = new TESBlockAleHorn();
		alloyForge = new TESBlockAlloyForge();
		appleCrumble = new TESBlockPlaceableFood();
		aridGrass = new TESBlockGrass().setSandy();
		armorStand = new TESBlockArmorStand();
		asshaiBars = new TESBlockBars();
		asshaiDirt = new TESBlockAsshaiDirt();
		asshaiFlower = new TESBlockAsshaiFlower();
		asshaiGrass = new TESBlockAsshaiGrass();
		asshaiMoss = new TESBlockAsshaiMoss();
		asshaiThorn = new TESBlockAsshaiThorn();
		asshaiTorch = new TESBlockAsshaiTorch().setHardness(0.0f).setStepSound(Block.soundTypeWood).setLightLevel(0.875f);
		banana = new TESBlockBanana().setHardness(0.0f).setResistance(1.0f).setStepSound(Block.soundTypeWood);
		bananaCake = new TESBlockPlaceableFood();
		bank = new TESBlockIronBank();
		barrel = new TESBlockBarrel();
		barrier = new TESBlockBarrier();
		basaltGravel = new TESBlockGravel();
		beacon = new TESBlockBeacon();
		berryBush = new TESBlockBerryBush();
		berryPie = new TESBlockPlaceableFood();
		birdCage = new TESBlockBirdCage();
		birdCageWood = new TESBlockBirdCageWood();
		blackroot = new TESBlockBlackroot();
		blockGem = new TESBlockGemStorage();
		blockMetal1 = new TESBlockMetal();
		blockMetal2 = new TESBlockMetal2();
		bluebell = new TESBlockFlower();
		bomb = new TESBlockBomb();
		boneBlock = new TESBlockBone();
		bookshelfStorage = new TESBlockBookshelfStorage();
		brick1 = new TESBlockBrick1();
		brick2 = new TESBlockBrick2();
		brick3 = new TESBlockBrick3();
		brick4 = new TESBlockBrick4();
		brick5 = new TESBlockBrick5();
		brick6 = new TESBlockBrick6();
		brickIce = new TESBlockBrickIce();
		bronzeBars = new TESBlockBars();
		butterflyJar = new TESBlockButterflyJar();
		buttonAndesite = new TESBlockButton(false, "TES:rock_andesite").setHardness(0.5f).setStepSound(Block.soundTypeStone);
		buttonBasalt = new TESBlockButton(false, "TES:rock_basalt").setHardness(0.5f).setStepSound(Block.soundTypeStone);
		buttonChalk = new TESBlockButton(false, "TES:rock_chalk").setHardness(0.5f).setStepSound(Block.soundTypeStone);
		buttonDiorite = new TESBlockButton(false, "TES:rock_diorite").setHardness(0.5f).setStepSound(Block.soundTypeStone);
		buttonGranite = new TESBlockButton(false, "TES:rock_granite").setHardness(0.5f).setStepSound(Block.soundTypeStone);
		buttonLabradorite = new TESBlockButton(false, "TES:rock_labradorite").setHardness(0.5f).setStepSound(Block.soundTypeStone);
		buttonRhyolite = new TESBlockButton(false, "TES:rock_rhyolite").setHardness(0.5f).setStepSound(Block.soundTypeStone);
		ceramicMug = new TESBlockClayMug();
		ceramicPlate = new TESBlockPlate().setStepSound(TESBlockPlate.SOUND_TYPE_PLATE);
		chain = new TESBlockChain();
		chandelier = new TESBlockChandelier();
		cherryPie = new TESBlockPlaceableFood();
		chestBasket = new TESBlockChest(Material.cloth, thatch, 1, "basket").setHardness(0.5f).setStepSound(Block.soundTypeCloth);
		chestSandstone = new TESBlockChest(Material.rock, brick1, 15, "essos").setHardness(3.0f).setStepSound(Block.soundTypeStone);
		chestStone = new TESBlockChest(Material.rock, Blocks.cobblestone, 0, "stone").setHardness(3.0f).setStepSound(Block.soundTypeStone);
		clayTile = new TESBlockClayTile();
		clayTileDyed = new TESBlockClayTileDyed();
		clover = new TESBlockClover();
		cobblebrick = new TESBlockCobblebrick();
		commandTable = new TESBlockCommandTable();
		coralReef = new TESBlockCoralReef();
		cornStalk = new TESBlockCorn();
		date = new TESBlockDate().setHardness(0.0f).setResistance(1.0f).setStepSound(Block.soundTypeWood);
		daub = new TESBlockDaub();
		deadMarshPlant = new TESBlockDeadPlant();
		dirtPath = new TESBlockDirtPath();
		doorAcacia = new TESBlockDoor().setCreativeTab(CreativeTabs.tabRedstone);
		doorAlmond = new TESBlockDoor();
		doorApple = new TESBlockDoor();
		doorAramant = new TESBlockDoor();
		doorAspen = new TESBlockDoor();
		doorBanana = new TESBlockDoor();
		doorBaobab = new TESBlockDoor();
		doorBeech = new TESBlockDoor();
		doorBirch = new TESBlockDoor().setCreativeTab(CreativeTabs.tabRedstone);
		doorCatalpa = new TESBlockDoor();
		doorCedar = new TESBlockDoor();
		doorCharred = new TESBlockDoor();
		doorCherry = new TESBlockDoor();
		doorChestnut = new TESBlockDoor();
		doorCypress = new TESBlockDoor();
		doorDarkOak = new TESBlockDoor().setCreativeTab(CreativeTabs.tabRedstone);
		doorDatePalm = new TESBlockDoor();
		doorDragon = new TESBlockDoor();
		doorFir = new TESBlockDoor();
		doorFotinia = new TESBlockDoor();
		doorGreenOak = new TESBlockDoor();
		doorHolly = new TESBlockDoor();
		doorIbbinia = new TESBlockDoor();
		doorJungle = new TESBlockDoor().setCreativeTab(CreativeTabs.tabRedstone);
		doorKanuka = new TESBlockDoor();
		doorLarch = new TESBlockDoor();
		doorLemon = new TESBlockDoor();
		doorLime = new TESBlockDoor();
		doorMahogany = new TESBlockDoor();
		doorMango = new TESBlockDoor();
		doorMangrove = new TESBlockDoor();
		doorMaple = new TESBlockDoor();
		doorOlive = new TESBlockDoor();
		doorOrange = new TESBlockDoor();
		doorPalm = new TESBlockDoor();
		doorPear = new TESBlockDoor();
		doorPine = new TESBlockDoor();
		doorPlum = new TESBlockDoor();
		doorPomegranate = new TESBlockDoor();
		doorRedwood = new TESBlockDoor();
		doorRotten = new TESBlockDoor();
		doorSpruce = new TESBlockDoor().setCreativeTab(CreativeTabs.tabRedstone);
		doorUlthos = new TESBlockDoor();
		doorWeirwood = new TESBlockDoor();
		doorWillow = new TESBlockDoor();
		doubleFlower = new TESBlockDoubleFlower();
		driedReeds = new TESBlockReedDry();
		essosFlower = new TESBlockEssosFlower();
		fallenLeaves1 = new TESBlockFallenLeaves();
		fallenLeaves2 = new TESBlockFallenLeaves();
		fallenLeaves3 = new TESBlockFallenLeaves();
		fallenLeaves4 = new TESBlockFallenLeaves();
		fence = new TESBlockFence(planks1);
		fence2 = new TESBlockFence(planks2);
		fence3 = new TESBlockFence(planks3);
		fenceGateAcacia = new TESBlockFenceGate(Blocks.planks, 4).setCreativeTab(CreativeTabs.tabRedstone);
		fenceGateAlmond = new TESBlockFenceGate(planks2, 15);
		fenceGateApple = new TESBlockFenceGate(planks1, 4);
		fenceGateAramant = new TESBlockFenceGate(planks1, 8);
		fenceGateAspen = new TESBlockFenceGate(planks2, 12);
		fenceGateBanana = new TESBlockFenceGate(planks1, 11);
		fenceGateBaobab = new TESBlockFenceGate(planks2, 1);
		fenceGateBeech = new TESBlockFenceGate(planks1, 9);
		fenceGateBirch = new TESBlockFenceGate(Blocks.planks, 2).setCreativeTab(CreativeTabs.tabRedstone);
		fenceGateCatalpa = new TESBlockFenceGate(planks1, 1);
		fenceGateCedar = new TESBlockFenceGate(planks2, 2);
		fenceGateCharred = new TESBlockFenceGate(planks1, 3);
		fenceGateCherry = new TESBlockFenceGate(planks1, 6);
		fenceGateChestnut = new TESBlockFenceGate(planks2, 0);
		fenceGateCypress = new TESBlockFenceGate(planks2, 10);
		fenceGateDarkOak = new TESBlockFenceGate(Blocks.planks, 5).setCreativeTab(CreativeTabs.tabRedstone);
		fenceGateDatePalm = new TESBlockFenceGate(planks1, 14);
		fenceGateDragon = new TESBlockFenceGate(planks3, 4);
		fenceGateFir = new TESBlockFenceGate(planks2, 3);
		fenceGateFotinia = new TESBlockFenceGate(planks2, 14);
		fenceGateGreenOak = new TESBlockFenceGate(planks2, 13);
		fenceGateHolly = new TESBlockFenceGate(planks1, 10);
		fenceGateIbbinia = new TESBlockFenceGate(planks1, 0);
		fenceGateJungle = new TESBlockFenceGate(Blocks.planks, 3).setCreativeTab(CreativeTabs.tabRedstone);
		fenceGateKanuka = new TESBlockFenceGate(planks3, 5);
		fenceGateLarch = new TESBlockFenceGate(planks1, 13);
		fenceGateLemon = new TESBlockFenceGate(planks2, 5);
		fenceGateLime = new TESBlockFenceGate(planks2, 7);
		fenceGateMahogany = new TESBlockFenceGate(planks2, 8);
		fenceGateMango = new TESBlockFenceGate(planks1, 7);
		fenceGateMangrove = new TESBlockFenceGate(planks1, 15);
		fenceGateMaple = new TESBlockFenceGate(planks1, 12);
		fenceGateOlive = new TESBlockFenceGate(planks2, 11);
		fenceGateOrange = new TESBlockFenceGate(planks2, 6);
		fenceGatePalm = new TESBlockFenceGate(planks3, 3);
		fenceGatePear = new TESBlockFenceGate(planks1, 5);
		fenceGatePine = new TESBlockFenceGate(planks2, 4);
		fenceGatePlum = new TESBlockFenceGate(planks3, 0);
		fenceGatePomegranate = new TESBlockFenceGate(planks3, 2);
		fenceGateRedwood = new TESBlockFenceGate(planks3, 1);
		fenceGateRotten = new TESBlockFenceGate(planksRotten, 0);
		fenceGateSpruce = new TESBlockFenceGate(Blocks.planks, 1).setCreativeTab(CreativeTabs.tabRedstone);
		fenceGateUlthos = new TESBlockFenceGate(planks1, 2);
		fenceGateWeirwood = new TESBlockFenceGate(planks3, 6);
		fenceGateWillow = new TESBlockFenceGate(planks2, 9);
		fenceRotten = new TESBlockFence(planksRotten);
		flaxCrop = new TESBlockFlaxCrop();
		flaxPlant = new TESBlockFlower().setFlowerBounds(0.2f, 0.0f, 0.2f, 0.8f, 0.8f, 0.8f);
		flowerPot = new TESBlockFlowerPot().setHardness(0.0f).setStepSound(Block.soundTypeStone);
		fruitLeaves = new TESBlockLeavesFruit();
		fruitSapling = new TESBlockSaplingFruit();
		fruitWood = new TESBlockFruitWood();
		furBed = new TESBlockBed(Blocks.planks, 0);
		fuse = new TESBlockDoubleTorch();
		gateBronzeBars = TESBlockGate.createMetal(false);
		gateEssos = TESBlockGate.createWooden(true);
		gateGold = TESBlockGate.createMetal(true);
		gateIbben = TESBlockGate.createWooden(true);
		gateIronBars = TESBlockGate.createMetal(false);
		gateSilver = TESBlockGate.createMetal(true);
		gateSothoryos = TESBlockGate.createWooden(true);
		gateValyrian = TESBlockGate.createMetal(true);
		gateWesteros = TESBlockGate.createWooden(true);
		gateWooden = TESBlockGate.createWooden(true);
		gateWoodenCross = TESBlockGate.createWooden(false);
		gateYiTi = TESBlockGate.createWooden(true);
		glass = new TESBlockGlass();
		glassBottle = new TESBlockGlassBottle();
		glassPane = new TESBlockGlassPane();
		gobletCopper = new TESBlockGoblet.Copper();
		gobletGold = new TESBlockGoblet.Gold();
		gobletSilver = new TESBlockGoblet.Silver();
		gobletWood = new TESBlockGoblet.Wood();
		goldBars = new TESBlockBars();
		grapevine = new TESBlockGrapevine(false);
		grapevineRed = new TESBlockGrapevineRed();
		grapevineWhite = new TESBlockGrapevineWhite();
		hearth = new TESBlockHearth().setHardness(1.0f).setResistance(8.0f).setStepSound(Block.soundTypeStone);
		kebabBlock = new TESBlockKebab();
		kebabStand = new TESBlockKebabStand("");
		kebabStandSand = new TESBlockKebabStand("sand");
		kelp = new TESBlockKelp();
		leaves1 = new TESBlockLeaves1();
		leaves2 = new TESBlockLeaves2();
		leaves3 = new TESBlockLeaves3();
		leaves4 = new TESBlockLeaves4();
		leaves5 = new TESBlockLeaves5();
		leaves6 = new TESBlockLeaves6();
		leaves7 = new TESBlockLeaves7();
		leaves8 = new TESBlockLeaves8();
		leaves9 = new TESBlockLeaves9();
		leekCrop = new TESBlockLeekCrop();
		lemonCake = new TESBlockPlaceableFood();
		lettuceCrop = new TESBlockLettuceCrop();
		lionBed = new TESBlockBed(Blocks.planks, 0);
		marigold = new TESBlockFlower();
		marshLights = new TESBlockMarshLights();
		marzipanBlock = new TESBlockPlaceableFood(0.4375f, 0.375f).setFoodStats(3, 0.3f).setCreativeTab(TESCreativeTabs.TAB_FOOD);
		millstone = new TESBlockMillstone();
		mirkVines = new TESBlockVine();
		mud = new TESBlockMud();
		mudFarmland = new TESBlockMudFarmland();
		mudGrass = new TESBlockMudGrass();
		mug = new TESBlockMug();
		obsidianGravel = new TESBlockObsidianGravel();
		oreCobalt = new TESBlockOre();
		oreCopper = new TESBlockOre();
		oreGem = new TESBlockOreGem();
		oreGlowstone = new TESBlockOre().setLightLevel(0.75f);
		oreSalt = new TESBlockOre();
		oreSaltpeter = new TESBlockOre();
		oreSilver = new TESBlockOre();
		oreSulfur = new TESBlockOre();
		oreTin = new TESBlockOre();
		oreValyrian = new TESBlockOre().setHardness(4.0f).setResistance(10.0f);
		oven = new TESBlockOven();
		pastry = new TESBlockPlaceableFood(0.3125f, 0.375f);
		pillar1 = new TESBlockPillar1();
		pillar2 = new TESBlockPillar2();
		pipeweedCrop = new TESBlockPipeweedCrop();
		pipeweedPlant = new TESBlockPipeweedPlant();
		plantain = new TESBlockPlantain();
		plate = new TESBlockPlate().setStepSound(TESBlockPlate.SOUND_TYPE_PLATE);
		pressurePlateAndesite = new TESBlockPressurePlate("TES:rock_andesite", Material.rock, BlockPressurePlate.Sensitivity.mobs).setHardness(0.5f).setStepSound(Block.soundTypeStone);
		pressurePlateBasalt = new TESBlockPressurePlate("TES:rock_basalt", Material.rock, BlockPressurePlate.Sensitivity.mobs).setHardness(0.5f).setStepSound(Block.soundTypeStone);
		pressurePlateChalk = new TESBlockPressurePlate("TES:rock_chalk", Material.rock, BlockPressurePlate.Sensitivity.mobs).setHardness(0.5f).setStepSound(Block.soundTypeStone);
		pressurePlateDiorite = new TESBlockPressurePlate("TES:rock_diorite", Material.rock, BlockPressurePlate.Sensitivity.mobs).setHardness(0.5f).setStepSound(Block.soundTypeStone);
		pressurePlateGranite = new TESBlockPressurePlate("TES:rock_granite", Material.rock, BlockPressurePlate.Sensitivity.mobs).setHardness(0.5f).setStepSound(Block.soundTypeStone);
		pressurePlateLabradorite = new TESBlockPressurePlate("TES:rock_labradorite", Material.rock, BlockPressurePlate.Sensitivity.mobs).setHardness(0.5f).setStepSound(Block.soundTypeStone);
		pressurePlateRhyolite = new TESBlockPressurePlate("TES:rock_rhyolite", Material.rock, BlockPressurePlate.Sensitivity.mobs).setHardness(0.5f).setStepSound(Block.soundTypeStone);
		quagmire = new TESBlockQuagmire().setHardness(1.0f).setStepSound(Block.soundTypeGravel);
		quicksand = new TESBlockQuicksand().setHardness(0.5f).setStepSound(Block.soundTypeSand);
		redBrick = new TESBlockBrickRed();
		redClay = new TESBlockRedClay();
		redSandstone = new TESBlockSandstone();
		reedBars = new TESBlockReedBars();
		reeds = new TESBlockReed();
		rock = new TESBlockRock();
		rope = new TESBlockRope(false);
		rottenLog = new TESBlockWoodRotten();
		rottenSlabDouble = new TESBlockSlabRotten(true).setHardness(2.0f).setResistance(5.0f).setStepSound(Block.soundTypeWood);
		rottenSlabSingle = new TESBlockSlabRotten(false).setHardness(2.0f).setResistance(5.0f).setStepSound(Block.soundTypeWood);
		sapling1 = new TESBlockSapling1();
		sapling2 = new TESBlockSapling2();
		sapling3 = new TESBlockSapling3();
		sapling4 = new TESBlockSapling4();
		sapling5 = new TESBlockSapling5();
		sapling6 = new TESBlockSapling6();
		sapling7 = new TESBlockSapling7();
		sapling8 = new TESBlockSapling8();
		sapling9 = new TESBlockSapling9();
		sarbacaneTrap = new TESBlockSarbacaneTrap(brick4, 0);
		sarbacaneTrapGold = new TESBlockSarbacaneTrap(brick4, 3);
		sarbacaneTrapObsidian = new TESBlockSarbacaneTrap(brick4, 4);
		scorchedSlabDouble = new TESBlockScorchedSlab(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		scorchedSlabSingle = new TESBlockScorchedSlab(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		scorchedStone = new TESBlockScorchedStone();
		scorchedWall = new TESBlockScorchedWall();
		signCarved = new TESBlockSignCarved(TESTileEntitySignCarved.class);
		signCarvedGlowing = new TESBlockSignCarved(TESTileEntitySignCarvedValyrian.class);
		silverBars = new TESBlockBars();
		skullCup = new TESBlockSkullCup();
		slabBoneDouble = new TESBlockSlabBone(true);
		slabBoneSingle = new TESBlockSlabBone(false);
		slabClayTileDouble = new TESBlockSlabClayTile(true);
		slabClayTileDyedDouble1 = new TESBlockSlabClayTileDyed(true);
		slabClayTileDyedDouble2 = new TESBlockSlabClayTileDyed2(true);
		slabClayTileDyedSingle1 = new TESBlockSlabClayTileDyed(false);
		slabClayTileDyedSingle2 = new TESBlockSlabClayTileDyed2(false);
		slabClayTileSingle = new TESBlockSlabClayTile(false);
		slabDouble1 = new TESBlockSlab1(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabDouble10 = new TESBlockSlab10(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabDouble11 = new TESBlockSlab11(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabDouble12 = new TESBlockSlab12(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabDouble2 = new TESBlockSlab2(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabDouble3 = new TESBlockSlab3(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabDouble4 = new TESBlockSlab4(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabDouble5 = new TESBlockSlab5(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabDouble6 = new TESBlockSlab6(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabDouble7 = new TESBlockSlab7(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabDouble8 = new TESBlockSlab8(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabDouble9 = new TESBlockSlab9(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabDoubleDirt = new TESBlockSlabDirt(true);
		slabDoubleGravel = new TESBlockSlabGravel(true);
		slabDoubleSand = new TESBlockSlabSand(true);
		slabDoubleThatch = new TESBlockSlabThatch(true);
		slabDoubleV = new TESBlockSlabV(true).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingle1 = new TESBlockSlab1(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingle10 = new TESBlockSlab10(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingle11 = new TESBlockSlab11(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingle12 = new TESBlockSlab12(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingle2 = new TESBlockSlab2(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingle3 = new TESBlockSlab3(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingle4 = new TESBlockSlab4(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingle5 = new TESBlockSlab5(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingle6 = new TESBlockSlab6(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingle7 = new TESBlockSlab7(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingle8 = new TESBlockSlab8(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingle9 = new TESBlockSlab9(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		slabSingleDirt = new TESBlockSlabDirt(false);
		slabSingleGravel = new TESBlockSlabGravel(false);
		slabSingleSand = new TESBlockSlabSand(false);
		slabSingleThatch = new TESBlockSlabThatch(false);
		slabSingleV = new TESBlockSlabV(false).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundTypeStone);
		smoothStone = new TESBlockSmoothStone();
		smoothStoneV = new TESBlockSmoothStoneV();
		sothoryosDoubleTorch = new TESBlockDoubleTorch();
		spawnerChest = new TESBlockSpawnerChest(Blocks.chest);
		spawnerChestAncientEssos = new TESBlockSpawnerChest(chestSandstone);
		spawnerChestStone = new TESBlockSpawnerChest(chestStone);
		stainedGlass = new TESBlockStainedGlass();
		stainedGlassPane = new TESBlockStainedGlassPane();
		stairsAlmond = new TESBlockStairs(planks2, 15);
		stairsAndesite = new TESBlockStairs(rock, 1);
		stairsAndesiteBrick = new TESBlockStairs(brick1, 1);
		stairsAndesiteBrickCracked = new TESBlockStairs(brick1, 3);
		stairsAndesiteBrickMossy = new TESBlockStairs(brick1, 2);
		stairsApple = new TESBlockStairs(planks1, 4);
		stairsAramant = new TESBlockStairs(planks1, 8);
		stairsAspen = new TESBlockStairs(planks2, 12);
		stairsBanana = new TESBlockStairs(planks1, 11);
		stairsBaobab = new TESBlockStairs(planks2, 1);
		stairsBasalt = new TESBlockStairs(rock, 0);
		stairsBasaltBrick = new TESBlockStairs(brick1, 0);
		stairsBasaltBrickCracked = new TESBlockStairs(brick1, 7);
		stairsBasaltWesterosBrick = new TESBlockStairs(brick2, 11);
		stairsBeech = new TESBlockStairs(planks1, 9);
		stairsBone = new TESBlockStairs(boneBlock, 0);
		stairsBrickCracked = new TESBlockStairs(redBrick, 1).setCreativeTab(CreativeTabs.tabBlock);
		stairsBrickMossy = new TESBlockStairs(redBrick, 0).setCreativeTab(CreativeTabs.tabBlock);
		stairsCatalpa = new TESBlockStairs(planks1, 1);
		stairsCedar = new TESBlockStairs(planks2, 2);
		stairsChalk = new TESBlockStairs(rock, 5);
		stairsChalkBrick = new TESBlockStairs(brick4, 15);
		stairsCharred = new TESBlockStairs(planks1, 3);
		stairsCherry = new TESBlockStairs(planks1, 6);
		stairsChestnut = new TESBlockStairs(planks2, 0);
		stairsClayTile = new TESBlockStairs(clayTile, 0);
		stairsClayTileDyedBlack = new TESBlockStairs(clayTileDyed, 15);
		stairsClayTileDyedBlue = new TESBlockStairs(clayTileDyed, 11);
		stairsClayTileDyedBrown = new TESBlockStairs(clayTileDyed, 12);
		stairsClayTileDyedCyan = new TESBlockStairs(clayTileDyed, 9);
		stairsClayTileDyedGray = new TESBlockStairs(clayTileDyed, 7);
		stairsClayTileDyedGreen = new TESBlockStairs(clayTileDyed, 13);
		stairsClayTileDyedLightBlue = new TESBlockStairs(clayTileDyed, 3);
		stairsClayTileDyedLightGray = new TESBlockStairs(clayTileDyed, 8);
		stairsClayTileDyedLime = new TESBlockStairs(clayTileDyed, 5);
		stairsClayTileDyedMagenta = new TESBlockStairs(clayTileDyed, 2);
		stairsClayTileDyedOrange = new TESBlockStairs(clayTileDyed, 1);
		stairsClayTileDyedPink = new TESBlockStairs(clayTileDyed, 6);
		stairsClayTileDyedPurple = new TESBlockStairs(clayTileDyed, 10);
		stairsClayTileDyedRed = new TESBlockStairs(clayTileDyed, 14);
		stairsClayTileDyedWhite = new TESBlockStairs(clayTileDyed, 0);
		stairsClayTileDyedYellow = new TESBlockStairs(clayTileDyed, 4);
		stairsCobblestoneMossy = new TESBlockStairs(Blocks.mossy_cobblestone, 0).setCreativeTab(CreativeTabs.tabBlock);
		stairsCypress = new TESBlockStairs(planks2, 10);
		stairsDatePalm = new TESBlockStairs(planks1, 14);
		stairsDiorite = new TESBlockStairs(rock, 3);
		stairsDioriteBrick = new TESBlockStairs(brick1, 14);
		stairsDragon = new TESBlockStairs(planks3, 4);
		stairsFir = new TESBlockStairs(planks2, 3);
		stairsFotinia = new TESBlockStairs(planks2, 14);
		stairsGranite = new TESBlockStairs(rock, 4);
		stairsGraniteBrick = new TESBlockStairs(brick2, 2);
		stairsGreenOak = new TESBlockStairs(planks2, 13);
		stairsHolly = new TESBlockStairs(planks1, 10);
		stairsIbbinia = new TESBlockStairs(planks1, 0);
		stairsKanuka = new TESBlockStairs(planks3, 5);
		stairsLabradorite = new TESBlockStairs(rock, 6);
		stairsLabradoriteBrick = new TESBlockStairs(brick6, 4);
		stairsLabradoriteBrickCracked = new TESBlockStairs(brick6, 6);
		stairsLabradoriteBrickMossy = new TESBlockStairs(brick6, 7);
		stairsLarch = new TESBlockStairs(planks1, 13);
		stairsLemon = new TESBlockStairs(planks2, 5);
		stairsLhazarBrick = new TESBlockStairs(brick3, 10);
		stairsLime = new TESBlockStairs(planks2, 7);
		stairsMahogany = new TESBlockStairs(planks2, 8);
		stairsMango = new TESBlockStairs(planks1, 7);
		stairsMangrove = new TESBlockStairs(planks1, 15);
		stairsMaple = new TESBlockStairs(planks1, 12);
		stairsMudBrick = new TESBlockStairs(brick5, 0);
		stairsOlive = new TESBlockStairs(planks2, 11);
		stairsOrange = new TESBlockStairs(planks2, 6);
		stairsPalm = new TESBlockStairs(planks3, 3);
		stairsPear = new TESBlockStairs(planks1, 5);
		stairsPine = new TESBlockStairs(planks2, 4);
		stairsPlum = new TESBlockStairs(planks3, 0);
		stairsPomegranate = new TESBlockStairs(planks3, 2);
		stairsRedSandstone = new TESBlockStairs(redSandstone, 0);
		stairsRedwood = new TESBlockStairs(planks3, 1);
		stairsReed = new TESBlockStairs(thatch, 1);
		stairsRhyolite = new TESBlockStairs(rock, 2);
		stairsRhyoliteBrick = new TESBlockStairs(brick1, 4);
		stairsRotten = new TESBlockStairs(planksRotten, 1);
		stairsSandstoneBrick = new TESBlockStairs(brick1, 15);
		stairsSandstoneBrickCracked = new TESBlockStairs(brick3, 11);
		stairsSandstoneBrickRed = new TESBlockStairs(brick3, 13);
		stairsSandstoneBrickRedCracked = new TESBlockStairs(brick3, 14);
		stairsScorchedStone = new TESBlockStairs(scorchedStone, 0);
		stairsSothoryosBrick = new TESBlockStairs(brick4, 0);
		stairsSothoryosBrickCracked = new TESBlockStairs(brick4, 2);
		stairsSothoryosBrickGold = new TESBlockStairs(brick4, 3);
		stairsSothoryosBrickMossy = new TESBlockStairs(brick4, 1);
		stairsSothoryosBrickObsidian = new TESBlockStairs(brick4, 4);
		stairsStone = new TESBlockStairs(Blocks.stone, 0).setCreativeTab(CreativeTabs.tabBlock);
		stairsStoneBrickCracked = new TESBlockStairs(Blocks.stonebrick, 2).setCreativeTab(CreativeTabs.tabBlock);
		stairsStoneBrickMossy = new TESBlockStairs(Blocks.stonebrick, 1).setCreativeTab(CreativeTabs.tabBlock);
		stairsThatch = new TESBlockStairs(thatch, 0);
		stairsUlthos = new TESBlockStairs(planks1, 2);
		stairsWeirwood = new TESBlockStairs(planks3, 6);
		stairsWhiteSandstone = new TESBlockStairs(whiteSandstone, 0);
		stairsWillow = new TESBlockStairs(planks2, 9);
		stairsYiTiBrick = new TESBlockStairs(brick5, 11);
		stairsYiTiBrickCracked = new TESBlockStairs(brick5, 14);
		stairsYiTiBrickFlowers = new TESBlockStairs(brick5, 15);
		stairsYiTiBrickMossy = new TESBlockStairs(brick5, 13);
		stairsYiTiBrickRed = new TESBlockStairs(brick6, 1);
		stalactite = new TESBlockStalactite(Blocks.stone, 0);
		stalactiteIce = new TESBlockStalactite(Blocks.packed_ice, 0);
		stalactiteObsidian = new TESBlockStalactite(Blocks.obsidian, 0);
		strawBed = new TESBlockBed(Blocks.planks, 0);
		tallGrass = new TESBlockTallGrass();
		termiteMound = new TESBlockTermite();
		thatchFloor = new TESBlockThatchFloor();
		trapdoorAcacia = new TESBlockTrapdoor().setCreativeTab(CreativeTabs.tabRedstone);
		trapdoorAlmond = new TESBlockTrapdoor();
		trapdoorApple = new TESBlockTrapdoor();
		trapdoorAramant = new TESBlockTrapdoor();
		trapdoorAspen = new TESBlockTrapdoor();
		trapdoorBanana = new TESBlockTrapdoor();
		trapdoorBaobab = new TESBlockTrapdoor();
		trapdoorBeech = new TESBlockTrapdoor();
		trapdoorBirch = new TESBlockTrapdoor().setCreativeTab(CreativeTabs.tabRedstone);
		trapdoorCatalpa = new TESBlockTrapdoor();
		trapdoorCedar = new TESBlockTrapdoor();
		trapdoorCharred = new TESBlockTrapdoor();
		trapdoorCherry = new TESBlockTrapdoor();
		trapdoorChestnut = new TESBlockTrapdoor();
		trapdoorCypress = new TESBlockTrapdoor();
		trapdoorDarkOak = new TESBlockTrapdoor().setCreativeTab(CreativeTabs.tabRedstone);
		trapdoorDatePalm = new TESBlockTrapdoor();
		trapdoorDragon = new TESBlockTrapdoor();
		trapdoorFir = new TESBlockTrapdoor();
		trapdoorFotinia = new TESBlockTrapdoor();
		trapdoorGreenOak = new TESBlockTrapdoor();
		trapdoorHolly = new TESBlockTrapdoor();
		trapdoorIbbinia = new TESBlockTrapdoor();
		trapdoorJungle = new TESBlockTrapdoor().setCreativeTab(CreativeTabs.tabRedstone);
		trapdoorKanuka = new TESBlockTrapdoor();
		trapdoorLarch = new TESBlockTrapdoor();
		trapdoorLemon = new TESBlockTrapdoor();
		trapdoorLime = new TESBlockTrapdoor();
		trapdoorMahogany = new TESBlockTrapdoor();
		trapdoorMango = new TESBlockTrapdoor();
		trapdoorMangrove = new TESBlockTrapdoor();
		trapdoorMaple = new TESBlockTrapdoor();
		trapdoorOlive = new TESBlockTrapdoor();
		trapdoorOrange = new TESBlockTrapdoor();
		trapdoorPalm = new TESBlockTrapdoor();
		trapdoorPear = new TESBlockTrapdoor();
		trapdoorPine = new TESBlockTrapdoor();
		trapdoorPlum = new TESBlockTrapdoor();
		trapdoorPomegranate = new TESBlockTrapdoor();
		trapdoorRedwood = new TESBlockTrapdoor();
		trapdoorRotten = new TESBlockTrapdoor();
		trapdoorSpruce = new TESBlockTrapdoor().setCreativeTab(CreativeTabs.tabRedstone);
		trapdoorUlthos = new TESBlockTrapdoor();
		trapdoorWeirwood = new TESBlockTrapdoor();
		trapdoorWillow = new TESBlockTrapdoor();
		treasureCopper = new TESBlockTreasurePile();
		treasureGold = new TESBlockTreasurePile();
		treasureSilver = new TESBlockTreasurePile();
		turnipCrop = new TESBlockTurnipCrop();
		unsmeltery = new TESBlockUnsmeltery();
		valyrianBars = new TESBlockBars();
		wallBone = new TESBlockWallBone();
		wallClayTile = new TESBlockWallClayTile();
		wallClayTileDyed = new TESBlockWallClayTileDyed();
		wallStone1 = new TESBlockWall1();
		wallStone2 = new TESBlockWall2();
		wallStone3 = new TESBlockWall3();
		wallStone4 = new TESBlockWall4();
		wallStoneV = new TESBlockWallV();
		wasteBlock = new TESBlockWaste();
		weaponRack = new TESBlockWeaponRack();
		whiteSand = new TESBlockSand();
		wildFire = new TESBlockWildFire();
		wildFireJar = new TESBlockWildFireJar();
		willowVines = new TESBlockVine();
		wineGlass = new TESBlockWineGlass();
		wood1 = new TESBlockWood1();
		wood2 = new TESBlockWood2();
		wood3 = new TESBlockWood3();
		wood4 = new TESBlockWood4();
		wood5 = new TESBlockWood5();
		wood6 = new TESBlockWood6();
		wood7 = new TESBlockWood7();
		wood8 = new TESBlockWood8();
		wood9 = new TESBlockWood9();
		woodBeam1 = new TESBlockWoodBeam1();
		woodBeam2 = new TESBlockWoodBeam2();
		woodBeam3 = new TESBlockWoodBeam3();
		woodBeam4 = new TESBlockWoodBeam4();
		woodBeam5 = new TESBlockWoodBeam5();
		woodBeam6 = new TESBlockWoodBeam6();
		woodBeam7 = new TESBlockWoodBeam7();
		woodBeam8 = new TESBlockWoodBeam8();
		woodBeam9 = new TESBlockWoodBeam9();
		woodBeamFruit = new TESBlockWoodBeamFruit();
		woodBeamRotten = new TESBlockWoodBeamRotten();
		woodBeamV1 = new TESBlockWoodBeamV1();
		woodBeamV2 = new TESBlockWoodBeamV2();
		woodPlate = new TESBlockPlate().setStepSound(Block.soundTypeWood);
		woodSlabDouble1 = new TESBlockWoodSlab1(true);
		woodSlabDouble2 = new TESBlockWoodSlab2(true).setHardness(2.0f).setResistance(5.0f).setStepSound(Block.soundTypeWood);
		woodSlabDouble3 = new TESBlockWoodSlab3(true);
		woodSlabDouble4 = new TESBlockWoodSlab4(true);
		woodSlabDouble5 = new TESBlockWoodSlab5(true);
		woodSlabSingle1 = new TESBlockWoodSlab1(false);
		woodSlabSingle2 = new TESBlockWoodSlab2(false).setHardness(2.0f).setResistance(5.0f).setStepSound(Block.soundTypeWood);
		woodSlabSingle3 = new TESBlockWoodSlab3(false);
		woodSlabSingle4 = new TESBlockWoodSlab4(false);
		woodSlabSingle5 = new TESBlockWoodSlab5(false);
		yamCrop = new TESBlockYamCrop();
		yitiFlower = new TESBlockYiTiFlower();
		
		tableEmpire = new TESBlockTableEmpire();
		
		oreOrichalcum = new TESBlockOre();
		
	}

	public static void onInit() {
		TESBlockSlabBase.registerSlabs(slabSingle1, slabDouble1);
		TESBlockSlabBase.registerSlabs(slabSingle2, slabDouble2);
		TESBlockSlabBase.registerSlabs(slabSingle3, slabDouble3);
		TESBlockSlabBase.registerSlabs(slabSingle4, slabDouble4);
		TESBlockSlabBase.registerSlabs(slabSingle5, slabDouble5);
		TESBlockSlabBase.registerSlabs(slabSingle6, slabDouble6);
		TESBlockSlabBase.registerSlabs(slabSingle7, slabDouble7);
		TESBlockSlabBase.registerSlabs(slabSingle8, slabDouble8);
		TESBlockSlabBase.registerSlabs(slabSingle9, slabDouble9);
		TESBlockSlabBase.registerSlabs(slabSingle10, slabDouble10);
		TESBlockSlabBase.registerSlabs(slabSingle11, slabDouble11);
		TESBlockSlabBase.registerSlabs(slabSingle12, slabDouble12);
		TESBlockSlabBase.registerSlabs(slabSingleV, slabDoubleV);
		TESBlockSlabBase.registerSlabs(scorchedSlabSingle, scorchedSlabDouble);
		TESBlockSlabBase.registerSlabs(slabClayTileSingle, slabClayTileDouble);
		TESBlockSlabBase.registerSlabs(slabClayTileDyedSingle1, slabClayTileDyedDouble1);
		TESBlockSlabBase.registerSlabs(slabClayTileDyedSingle2, slabClayTileDyedDouble2);
		TESBlockSlabBase.registerSlabs(woodSlabSingle1, woodSlabDouble1);
		TESBlockSlabBase.registerSlabs(woodSlabSingle2, woodSlabDouble2);
		TESBlockSlabBase.registerSlabs(woodSlabSingle3, woodSlabDouble3);
		TESBlockSlabBase.registerSlabs(woodSlabSingle4, woodSlabDouble4);
		TESBlockSlabBase.registerSlabs(woodSlabSingle5, woodSlabDouble5);
		TESBlockSlabBase.registerSlabs(rottenSlabSingle, rottenSlabDouble);
		TESBlockSlabBase.registerSlabs(slabSingleThatch, slabDoubleThatch);
		TESBlockSlabBase.registerSlabs(slabSingleDirt, slabDoubleDirt);
		TESBlockSlabBase.registerSlabs(slabSingleSand, slabDoubleSand);
		TESBlockSlabBase.registerSlabs(slabSingleGravel, slabDoubleGravel);
		TESBlockSlabBase.registerSlabs(slabBoneSingle, slabBoneDouble);
		TESBlockFallenLeaves.assignLeaves(fallenLeaves1, Blocks.leaves, Blocks.leaves2);
		TESBlockFallenLeaves.assignLeaves(fallenLeaves2, leaves1, fruitLeaves, leaves2, leaves3);
		TESBlockFallenLeaves.assignLeaves(fallenLeaves3, leaves4, leaves5, leaves6, leaves7);
		TESBlockFallenLeaves.assignLeaves(fallenLeaves4, leaves8, leaves9);

		for (Block block : CONTENT) {
			if (block instanceof TESBlockWoodBase) {
				Blocks.fire.setFireInfo(block, 5, 5);
			}
			if (block instanceof TESBlockPlanksBase || block instanceof TESBlockFence || block instanceof TESBlockWoodBeam || (block instanceof TESBlockSlabBase || block instanceof TESBlockStairs) && block.getMaterial() == Material.wood) {
				Blocks.fire.setFireInfo(block, 5, 20);
			}
			if (block instanceof TESBlockVine) {
				Blocks.fire.setFireInfo(block, 15, 100);
			}
			if (block instanceof TESBlockLeavesBase || block instanceof TESBlockFallenLeaves || block instanceof TESBlockBerryBush) {
				Blocks.fire.setFireInfo(block, 30, 60);
			}
			if (block instanceof TESBlockDaub) {
				Blocks.fire.setFireInfo(block, 40, 40);
			}
			if (block instanceof TESBlockThatch || block instanceof TESBlockThatchFloor || block instanceof TESBlockReedBars || (block instanceof TESBlockSlabBase || block instanceof TESBlockStairs) && block.getMaterial() == Material.grass) {
				Blocks.fire.setFireInfo(block, 60, 20);
			}
			if (block instanceof TESBlockThatch || block instanceof TESBlockThatchFloor || block instanceof TESBlockReedBars || block instanceof TESBlockGrass || block instanceof TESBlockAsshaiGrass || block instanceof TESBlockAsshaiMoss || block instanceof TESBlockFlower || block instanceof TESBlockDoubleFlower) {
				Blocks.fire.setFireInfo(block, 60, 100);
			}
		}
		Blocks.dragon_egg.setCreativeTab(TESCreativeTabs.TAB_STORY);
		Blocks.fire.setFireInfo(Blocks.acacia_stairs, 5, 20);
		Blocks.fire.setFireInfo(Blocks.dark_oak_stairs, 5, 20);
		Blocks.fire.setFireInfo(Blocks.leaves, 30, 60);
		Blocks.fire.setFireInfo(Blocks.leaves2, 30, 60);
		String pickaxe = "pickaxe";
		String shovel = "shovel";
		oreCopper.setHarvestLevel(pickaxe, 1);
		oreTin.setHarvestLevel(pickaxe, 1);
		oreSilver.setHarvestLevel(pickaxe, 2);
		oreCobalt.setHarvestLevel(pickaxe, 2);
		blockMetal1.setHarvestLevel(pickaxe, 1, 0);
		blockMetal1.setHarvestLevel(pickaxe, 1, 1);
		blockMetal1.setHarvestLevel(pickaxe, 1, 2);
		blockMetal1.setHarvestLevel(pickaxe, 2, 3);
		blockMetal1.setHarvestLevel(pickaxe, 2, 4);
		oreGlowstone.setHarvestLevel(pickaxe, 1);
		quagmire.setHarvestLevel(shovel, 0);
		quicksand.setHarvestLevel(shovel, 0);
		blockMetal2.setHarvestLevel(pickaxe, 1, 4);
		asshaiDirt.setHarvestLevel(shovel, 0);
		basaltGravel.setHarvestLevel(shovel, 0);
		obsidianGravel.setHarvestLevel(shovel, 0);
		mud.setHarvestLevel(shovel, 0);
		mudGrass.setHarvestLevel(shovel, 0);
		mudFarmland.setHarvestLevel(shovel, 0);
		dirtPath.setHarvestLevel(shovel, 0);
		slabSingleDirt.setHarvestLevel(shovel, 0);
		slabDoubleDirt.setHarvestLevel(shovel, 0);
		slabSingleSand.setHarvestLevel(shovel, 0);
		slabDoubleSand.setHarvestLevel(shovel, 0);
		slabSingleGravel.setHarvestLevel(shovel, 0);
		slabDoubleGravel.setHarvestLevel(shovel, 0);
		whiteSand.setHarvestLevel(shovel, 0);
		stalactiteObsidian.setHarvestLevel(pickaxe, 3);
		oreGem.setHarvestLevel(pickaxe, 2);
		blockGem.setHarvestLevel(pickaxe, 2);
		blockGem.setHarvestLevel(pickaxe, 0, 8);
		redClay.setHarvestLevel(shovel, 0);
	}

	public static void preInit() {
		TESBlockReplacement.replaceVanillaBlock(Blocks.leaves, new TESBlockLeavesVanilla1(), ItemLeaves.class);
		TESBlockReplacement.replaceVanillaBlock(Blocks.leaves2, new TESBlockLeavesVanilla2(), ItemLeaves.class);
		TESBlockReplacement.replaceVanillaBlock(Blocks.fence, new TESBlockFenceVanilla(), TESItemFenceVanilla.class);
		TESBlockReplacement.replaceVanillaBlock(Blocks.cake, new TESBlockPlaceableFood().setBlockTextureName("cake"), null);
		assignContent();
		registerContent();
	}

	public static void register(Block block, String codename) {
		register(block, codename, ItemBlock.class);
	}

	public static void register(Block block, String codename, Class<? extends ItemBlock> itemClass) {
		String lowerUnderscoreName = CaseFormat.LOWER_CAMEL.to(CaseFormat.LOWER_UNDERSCORE, codename);
		block.setBlockName("tes:" + lowerUnderscoreName);
		block.setBlockTextureName("tes:" + lowerUnderscoreName);
		GameRegistry.registerBlock(block, itemClass, "tile." + lowerUnderscoreName);
		CONTENT.add(block);
	}

	private static void registerContent() {
		/* blocks */

		register(rock, "rock", TESItemBlockMetadata.class);
		register(smoothStone, "smoothStone", TESItemBlockMetadata.class);

		register(oreSalt, "oreSalt");
		register(oreSaltpeter, "oreSaltpeter");
		register(oreSulfur, "oreSulfur");
		register(oreGlowstone, "oreGlowstone");

		register(oreCobalt, "oreCobalt");
		register(oreTin, "oreTin");
		register(oreCopper, "oreCopper");
		register(oreSilver, "oreSilver");
		register(oreOrichalcum, "oreOrichalcum");
		register(blockMetal1, "blockMetal1", TESItemBlockMetadata.class);
		register(blockMetal2, "blockMetal2", TESItemBlockMetadata.class);

		register(oreGem, "oreGem", TESItemBlockMetadata.class);

		register(blockGem, "blockGem", TESItemBlockMetadata.class);

		register(brick1, "brick1", TESItemBlockMetadata.class);
		register(brick2, "brick2", TESItemBlockMetadata.class);
		register(brick3, "brick3", TESItemBlockMetadata.class);
		register(brick4, "brick4", TESItemBlockMetadata.class);
		register(brick5, "brick5", TESItemBlockMetadata.class);
		register(brick6, "brick6", TESItemBlockMetadata.class);
		register(brickIce, "brickIce");

		register(pillar1, "pillar1", TESItemBlockMetadata.class);
		register(pillar2, "pillar2", TESItemBlockMetadata.class);

		register(wallStone1, "wallStone1", TESItemBlockMetadata.class);
		register(wallStone2, "wallStone2", TESItemBlockMetadata.class);
		register(wallStone3, "wallStone3", TESItemBlockMetadata.class);
		register(wallStone4, "wallStone4", TESItemBlockMetadata.class);

		register(slabSingle1, "slabSingle1", TESBlockSlabBase.SlabItems.Slab1Single.class);
		register(slabSingle2, "slabSingle2", TESBlockSlabBase.SlabItems.Slab2Single.class);
		register(slabSingle3, "slabSingle3", TESBlockSlabBase.SlabItems.Slab3Single.class);
		register(slabSingle4, "slabSingle4", TESBlockSlabBase.SlabItems.Slab4Single.class);
		register(slabSingle5, "slabSingle5", TESBlockSlabBase.SlabItems.Slab5Single.class);
		register(slabSingle6, "slabSingle6", TESBlockSlabBase.SlabItems.Slab13Single.class);
		register(slabSingle7, "slabSingle7", TESBlockSlabBase.SlabItems.Slab7Single.class);
		register(slabSingle8, "slabSingle8", TESBlockSlabBase.SlabItems.Slab8Single.class);
		register(slabSingle9, "slabSingle9", TESBlockSlabBase.SlabItems.Slab9Single.class);
		register(slabSingle10, "slabSingle10", TESBlockSlabBase.SlabItems.Slab10Single.class);
		register(slabSingle11, "slabSingle11", TESBlockSlabBase.SlabItems.Slab11Single.class);
		register(slabSingle12, "slabSingle12", TESBlockSlabBase.SlabItems.Slab12Single.class);
		register(rottenSlabSingle, "rottenSlabSingle", TESBlockSlabBase.SlabItems.RottenSlabSingle.class);

		register(stairsAndesite, "stairsAndesite");
		register(stairsAndesiteBrick, "stairsAndesiteBrick");
		register(stairsAndesiteBrickCracked, "stairsAndesiteBrickCracked");
		register(stairsAndesiteBrickMossy, "stairsAndesiteBrickMossy");
		register(stairsBasalt, "stairsBasalt");
		register(stairsBasaltBrick, "stairsBasaltBrick");
		register(stairsBasaltBrickCracked, "stairsBasaltBrickCracked");
		register(stairsBasaltWesterosBrick, "stairsBasaltWesterosBrick");
		register(stairsDiorite, "stairsDiorite");
		register(stairsDioriteBrick, "stairsDioriteBrick");
		register(stairsGranite, "stairsGranite");
		register(stairsGraniteBrick, "stairsGraniteBrick");
		register(stairsLabradorite, "stairsLabradorite");
		register(stairsLabradoriteBrick, "stairsLabradoriteBrick");
		register(stairsLabradoriteBrickCracked, "stairsLabradoriteBrickCracked");
		register(stairsLabradoriteBrickMossy, "stairsLabradoriteBrickMossy");
		register(stairsRhyolite, "stairsRhyolite");
		register(stairsRhyoliteBrick, "stairsRhyoliteBrick");
		register(stairsSandstoneBrick, "stairsSandstoneBrick");
		register(stairsSandstoneBrickCracked, "stairsSandstoneBrickCracked");
		register(stairsSandstoneBrickRed, "stairsSandstoneBrickRed");
		register(stairsSandstoneBrickRedCracked, "stairsSandstoneBrickRedCracked");
		register(stairsSothoryosBrick, "stairsSothoryosBrick");
		register(stairsSothoryosBrickCracked, "stairsSothoryosBrickCracked");
		register(stairsSothoryosBrickGold, "stairsSothoryosBrickGold");
		register(stairsSothoryosBrickMossy, "stairsSothoryosBrickMossy");
		register(stairsSothoryosBrickObsidian, "stairsSothoryosBrickObsidian");
		register(stairsYiTiBrick, "stairsYiTiBrick");
		register(stairsYiTiBrickCracked, "stairsYiTiBrickCracked");
		register(stairsYiTiBrickFlowers, "stairsYiTiBrickFlowers");
		register(stairsYiTiBrickMossy, "stairsYiTiBrickMossy");
		register(stairsYiTiBrickRed, "stairsYiTiBrickRed");
		register(stairsLhazarBrick, "stairsLhazarBrick");

		register(wood1, "wood1", TESItemBlockMetadata.class);
		register(wood2, "wood2", TESItemBlockMetadata.class);
		register(wood3, "wood3", TESItemBlockMetadata.class);
		register(wood4, "wood4", TESItemBlockMetadata.class);
		register(wood5, "wood5", TESItemBlockMetadata.class);
		register(wood6, "wood6", TESItemBlockMetadata.class);
		register(wood7, "wood7", TESItemBlockMetadata.class);
		register(wood8, "wood8", TESItemBlockMetadata.class);
		register(wood9, "wood9", TESItemBlockMetadata.class);
		register(fruitWood, "fruitWood", TESItemBlockMetadata.class);
		register(rottenLog, "rottenLog", TESItemBlockMetadata.class);

		register(woodBeamV1, "woodBeamV1", TESItemBlockMetadata.class);
		register(woodBeamV2, "woodBeamV2", TESItemBlockMetadata.class);
		register(woodBeam1, "woodBeam1", TESItemBlockMetadata.class);
		register(woodBeam2, "woodBeam2", TESItemBlockMetadata.class);
		register(woodBeam3, "woodBeam3", TESItemBlockMetadata.class);
		register(woodBeam4, "woodBeam4", TESItemBlockMetadata.class);
		register(woodBeam5, "woodBeam5", TESItemBlockMetadata.class);
		register(woodBeam6, "woodBeam6", TESItemBlockMetadata.class);
		register(woodBeam7, "woodBeam7", TESItemBlockMetadata.class);
		register(woodBeam8, "woodBeam8", TESItemBlockMetadata.class);
		register(woodBeam9, "woodBeam9", TESItemBlockMetadata.class);
		register(woodBeamFruit, "woodBeamFruit", TESItemBlockMetadata.class);
		register(woodBeamRotten, "woodBeamRotten", TESItemBlockMetadata.class);

		register(planks1, "planks1", TESItemBlockMetadata.class);
		register(planks2, "planks2", TESItemBlockMetadata.class);
		register(planks3, "planks3", TESItemBlockMetadata.class);
		register(planksRotten, "planksRotten", TESItemBlockMetadata.class);

		register(woodSlabSingle1, "woodSlabSingle1", TESBlockSlabBase.SlabItems.WoodSlab1Single.class);
		register(woodSlabSingle2, "woodSlabSingle2", TESBlockSlabBase.SlabItems.WoodSlab2Single.class);
		register(woodSlabSingle3, "woodSlabSingle3", TESBlockSlabBase.SlabItems.WoodSlab3Single.class);
		register(woodSlabSingle4, "woodSlabSingle4", TESBlockSlabBase.SlabItems.WoodSlab4Single.class);
		register(woodSlabSingle5, "woodSlabSingle5", TESBlockSlabBase.SlabItems.WoodSlab5Single.class);

		register(stairsAlmond, "stairsAlmond");
		register(stairsApple, "stairsApple");
		register(stairsAramant, "stairsAramant");
		register(stairsAspen, "stairsAspen");
		register(stairsBanana, "stairsBanana");
		register(stairsBaobab, "stairsBaobab");
		register(stairsBeech, "stairsBeech");
		register(stairsCatalpa, "stairsCatalpa");
		register(stairsCedar, "stairsCedar");
		register(stairsCherry, "stairsCherry");
		register(stairsChestnut, "stairsChestnut");
		register(stairsCypress, "stairsCypress");
		register(stairsDatePalm, "stairsDatePalm");
		register(stairsDragon, "stairsDragon");
		register(stairsFir, "stairsFir");
		register(stairsFotinia, "stairsFotinia");
		register(stairsGreenOak, "stairsGreenOak");
		register(stairsHolly, "stairsHolly");
		register(stairsIbbinia, "stairsIbbinia");
		register(stairsKanuka, "stairsKanuka");
		register(stairsLarch, "stairsLarch");
		register(stairsLemon, "stairsLemon");
		register(stairsLime, "stairsLime");
		register(stairsMahogany, "stairsMahogany");
		register(stairsMango, "stairsMango");
		register(stairsMangrove, "stairsMangrove");
		register(stairsMaple, "stairsMaple");
		register(stairsOlive, "stairsOlive");
		register(stairsOrange, "stairsOrange");
		register(stairsPalm, "stairsPalm");
		register(stairsPear, "stairsPear");
		register(stairsPine, "stairsPine");
		register(stairsPlum, "stairsPlum");
		register(stairsPomegranate, "stairsPomegranate");
		register(stairsRedwood, "stairsRedwood");
		register(stairsUlthos, "stairsUlthos");
		register(stairsWeirwood, "stairsWeirwood");
		register(stairsWillow, "stairsWillow");
		register(stairsCharred, "stairsCharred");
		register(stairsRotten, "stairsRotten");

		register(scorchedStone, "scorchedStone");
		register(scorchedWall, "scorchedWall");
		register(scorchedSlabSingle, "scorchedSlabSingle", TESBlockSlabBase.SlabItems.ScorchedSingle.class);
		register(stairsScorchedStone, "stairsScorchedStone");

		register(boneBlock, "boneBlock");
		register(wallBone, "wallBone", TESItemBlockMetadata.class);
		register(slabBoneSingle, "slabBoneSingle", TESBlockSlabBase.SlabItems.BoneSingle.class);
		register(stairsBone, "stairsBone");

		register(thatch, "thatch", TESItemBlockMetadata.class);
		register(slabSingleThatch, "slabSingleThatch", TESBlockSlabBase.SlabItems.ThatchSingle.class);
		register(stairsThatch, "stairsThatch");
		register(stairsReed, "stairsReed");

		register(dirtPath, "dirtPath", TESItemBlockMetadata.class);
		register(cobblebrick, "cobblebrick", TESItemBlockMetadata.class);
		register(daub, "daub");
		register(hearth, "hearth");
		register(wasteBlock, "wasteBlock");

		register(asshaiDirt, "asshaiDirt");
		register(basaltGravel, "basaltGravel");
		register(obsidianGravel, "obsidianGravel");

		register(mud, "mud", TESItemBlockMetadata.class);
		register(mudGrass, "mudGrass");
		register(stairsMudBrick, "stairsMudBrick");

		register(stairsChalk, "stairsChalk");
		register(stairsChalkBrick, "stairsChalkBrick");

		register(redSandstone, "redSandstone");
		register(stairsRedSandstone, "stairsRedSandstone");

		register(whiteSand, "whiteSand");
		register(whiteSandstone, "whiteSandstone");
		register(stairsWhiteSandstone, "stairsWhiteSandstone");

		register(quagmire, "quagmire");
		register(quicksand, "quicksand");
		register(redClay, "redClay");

		register(coralReef, "coralReef");
		register(termiteMound, "termiteMound", TESItemBlockMetadata.class);

		register(slabSingleDirt, "slabSingleDirt", TESBlockSlabBase.SlabItems.DirtSingle.class);
		register(slabSingleGravel, "slabSingleGravel", TESBlockSlabBase.SlabItems.GravelSingle.class);
		register(slabSingleSand, "slabSingleSand", TESBlockSlabBase.SlabItems.SandSingle.class);

		register(glass, "glass");
		register(stainedGlass, "stainedGlass", TESItemBlockMetadata.class);

		register(clayTile, "clayTile");
		register(clayTileDyed, "clayTileDyed", TESItemBlockMetadata.class);

		register(wallClayTile, "wallClayTile", TESItemBlockMetadata.class);
		register(wallClayTileDyed, "wallClayTileDyed", TESItemBlockMetadata.class);

		register(slabClayTileSingle, "slabClayTileSingle", TESBlockSlabBase.SlabItems.ClayTileSingle.class);

		register(slabClayTileDyedSingle1, "slabClayTileDyedSingle1", TESBlockSlabBase.SlabItems.ClayTileDyedSingle.class);
		register(slabClayTileDyedSingle2, "slabClayTileDyedSingle2", TESBlockSlabBase.SlabItems.ClayTileDyed2Single.class);

		register(stairsClayTile, "stairsClayTile");
		register(stairsClayTileDyedBlack, "stairsClayTileDyedBlack");
		register(stairsClayTileDyedBlue, "stairsClayTileDyedBlue");
		register(stairsClayTileDyedBrown, "stairsClayTileDyedBrown");
		register(stairsClayTileDyedCyan, "stairsClayTileDyedCyan");
		register(stairsClayTileDyedGray, "stairsClayTileDyedGray");
		register(stairsClayTileDyedGreen, "stairsClayTileDyedGreen");
		register(stairsClayTileDyedLightBlue, "stairsClayTileDyedLightBlue");
		register(stairsClayTileDyedLightGray, "stairsClayTileDyedLightGray");
		register(stairsClayTileDyedLime, "stairsClayTileDyedLime");
		register(stairsClayTileDyedMagenta, "stairsClayTileDyedMagenta");
		register(stairsClayTileDyedOrange, "stairsClayTileDyedOrange");
		register(stairsClayTileDyedPink, "stairsClayTileDyedPink");
		register(stairsClayTileDyedPurple, "stairsClayTileDyedPurple");
		register(stairsClayTileDyedRed, "stairsClayTileDyedRed");
		register(stairsClayTileDyedWhite, "stairsClayTileDyedWhite");
		register(stairsClayTileDyedYellow, "stairsClayTileDyedYellow");

		for (TESEnumDyeColor color : TESEnumDyeColor.values()) {
			CONCRETE_POWDER.put(color, new TESBlockConcretePowder(color));
			CONCRETE.put(color, new TESBlockConcrete(color));
			register(CONCRETE_POWDER.get(color), "concrete_powder_" + color.getUnlocalizedName(), TESItemBlockConcrete.class);
			register(CONCRETE.get(color), "concrete_" + color.getUnlocalizedName(), TESItemBlockConcrete.class);
		}

		/* buildingBlocks */

		register(redBrick, "redBrick", TESItemBlockMetadata.class);
		register(slabSingleV, "slabSingleV", TESBlockSlabBase.SlabItems.SlabVSingle.class);
		register(smoothStoneV, "smoothStoneV", TESItemBlockMetadata.class);
		register(stairsBrickCracked, "stairsBrickCracked");
		register(stairsBrickMossy, "stairsBrickMossy");
		register(stairsCobblestoneMossy, "stairsCobblestoneMossy");
		register(stairsStone, "stairsStone");
		register(stairsStoneBrickCracked, "stairsStoneBrickCracked");
		register(stairsStoneBrickMossy, "stairsStoneBrickMossy");
		register(wallStoneV, "wallStoneV", TESItemBlockMetadata.class);

		/* combat */

		register(bomb, "bomb", TESItemBomb.class);
		register(wildFireJar, "wildFireJar", TESItemWildFireJar.class);

		/* decorations */

		register(sapling1, "sapling1", TESItemBlockMetadata.class);
		register(sapling2, "sapling2", TESItemBlockMetadata.class);
		register(sapling3, "sapling3", TESItemBlockMetadata.class);
		register(sapling4, "sapling4", TESItemBlockMetadata.class);
		register(sapling5, "sapling5", TESItemBlockMetadata.class);
		register(sapling6, "sapling6", TESItemBlockMetadata.class);
		register(sapling7, "sapling7", TESItemBlockMetadata.class);
		register(sapling8, "sapling8", TESItemBlockMetadata.class);
		register(sapling9, "sapling9", TESItemBlockMetadata.class);
		register(fruitSapling, "fruitSapling", TESItemBlockMetadata.class);

		register(leaves1, "leaves1", TESItemLeaves.class);
		register(leaves2, "leaves2", TESItemLeaves.class);
		register(leaves3, "leaves3", TESItemLeaves.class);
		register(leaves4, "leaves4", TESItemLeaves.class);
		register(leaves5, "leaves5", TESItemLeaves.class);
		register(leaves6, "leaves6", TESItemLeaves.class);
		register(leaves7, "leaves7", TESItemLeaves.class);
		register(leaves8, "leaves8", TESItemLeaves.class);
		register(leaves9, "leaves9", TESItemLeaves.class);
		register(fruitLeaves, "fruitLeaves", TESItemLeaves.class);

		register(fallenLeaves1, "fallenLeaves1", TESItemFallenLeaves.class);
		register(fallenLeaves2, "fallenLeaves2", TESItemFallenLeaves.class);
		register(fallenLeaves3, "fallenLeaves3", TESItemFallenLeaves.class);
		register(fallenLeaves4, "fallenLeaves4", TESItemFallenLeaves.class);

		register(fence, "fence", TESItemBlockMetadata.class);
		register(fence2, "fence2", TESItemBlockMetadata.class);
		register(fence3, "fence3", TESItemBlockMetadata.class);
		register(fenceRotten, "fenceRotten", TESItemBlockMetadata.class);

		register(berryBush, "berryBush", TESItemBlockMetadata.class);

		register(aridGrass, "aridGrass");
		register(asshaiFlower, "asshaiFlower");
		register(asshaiGrass, "asshaiGrass");
		register(asshaiMoss, "asshaiMoss");
		register(asshaiThorn, "asshaiThorn");
		register(blackroot, "blackroot");
		register(bluebell, "bluebell");
		register(clover, "clover", TESItemBlockMetadata.class);
		register(cornStalk, "cornStalk", TESItemPlantableBlock.class);
		register(deadMarshPlant, "deadMarshPlant");
		register(doubleFlower, "doubleFlower", TESItemDoubleFlower.class);
		register(driedReeds, "driedReeds", TESItemReeds.class);
		register(essosFlower, "essosFlower", TESItemBlockMetadata.class);
		register(flaxPlant, "flaxPlant");
		register(grapevine, "grapevine");
		register(kelp, "kelp", TESItemKelp.class);
		register(marigold, "marigold");
		register(mirkVines, "mirkVines", TESItemVine.class);
		register(pipeweedPlant, "pipeweedPlant");
		register(plantain, "plantain");
		register(reeds, "reeds", TESItemReeds.class);
		register(tallGrass, "tallGrass", TESItemTallGrass.class);
		register(willowVines, "willowVines", TESItemVine.class);
		register(yitiFlower, "yitiFlower", TESItemBlockMetadata.class);

		register(treasureCopper, "treasureCopper", TESItemTreasurePile.class);
		register(treasureSilver, "treasureSilver", TESItemTreasurePile.class);
		register(treasureGold, "treasureGold", TESItemTreasurePile.class);

		register(bronzeBars, "bronzeBars");
		register(silverBars, "silverBars");
		register(goldBars, "goldBars");
		register(valyrianBars, "valyrianBars");

		register(chandelier, "chandelier", TESItemBlockMetadata.class);

		register(birdCage, "birdCage", TESItemAnimalJar.class);
		register(birdCageWood, "birdCageWood", TESItemAnimalJar.class);

		register(asshaiTorch, "asshaiTorch");
		register(butterflyJar, "butterflyJar", TESItemAnimalJar.class);
		register(weaponRack, "weaponRack", TESItemBlockWeaponRack.class);
		register(rope, "rope");
		register(thatchFloor, "thatchFloor");

		register(reedBars, "reedBars");
		register(asshaiBars, "asshaiBars");

		register(glassPane, "glassPane");
		register(stainedGlassPane, "stainedGlassPane", TESItemBlockMetadata.class);

		register(stalactite, "stalactite", TESItemBlockMetadata.class);
		register(stalactiteIce, "stalactiteIce", TESItemBlockMetadata.class);
		register(stalactiteObsidian, "stalactiteObsidian", TESItemBlockMetadata.class);

		/* food */

		register(barrel, "barrel", TESItemBarrel.class);
		register(kebabBlock, "kebabBlock");
		register(marzipanBlock, "marzipanBlock");

		/* misc */

		register(pressurePlateAndesite, "pressurePlateAndesite");
		register(pressurePlateBasalt, "pressurePlateBasalt");
		register(pressurePlateChalk, "pressurePlateChalk");
		register(pressurePlateDiorite, "pressurePlateDiorite");
		register(pressurePlateGranite, "pressurePlateGranite");
		register(pressurePlateLabradorite, "pressurePlateLabradorite");
		register(pressurePlateRhyolite, "pressurePlateRhyolite");

		register(buttonAndesite, "buttonAndesite");
		register(buttonBasalt, "buttonBasalt");
		register(buttonChalk, "buttonChalk");
		register(buttonDiorite, "buttonDiorite");
		register(buttonGranite, "buttonGranite");
		register(buttonLabradorite, "buttonLabradorite");
		register(buttonRhyolite, "buttonRhyolite");

		/* null */

		register(aleHorn, "aleHorn");
		register(aleHornGold, "aleHornGold");
		register(appleCrumble, "appleCrumble");
		register(armorStand, "armorStand");
		register(banana, "banana");
		register(bananaCake, "bananaCake");
		register(berryPie, "berryPie");
		register(bookshelfStorage, "bookshelfStorage");
		register(ceramicMug, "ceramicMug");
		register(ceramicPlate, "ceramicPlate");
		register(cherryPie, "cherryPie");
		register(date, "date");
		register(flaxCrop, "flax");
		register(flowerPot, "flowerPot");
		register(furBed, "furBed");
		register(fuse, "fuse");
		register(glassBottle, "glassBottle");
		register(gobletCopper, "gobletCopper");
		register(gobletGold, "gobletGold");
		register(gobletSilver, "gobletSilver");
		register(gobletWood, "gobletWood");
		register(grapevineRed, "grapevineRed");
		register(grapevineWhite, "grapevineWhite");
		register(leekCrop, "leek");
		register(lemonCake, "lemonCake");
		register(lettuceCrop, "lettuce");
		register(lionBed, "lionBed");
		register(marshLights, "marshLights");
		register(mudFarmland, "mudFarmland");
		register(mug, "mug");
		register(pastry, "pastry");
		register(pipeweedCrop, "pipeweed");
		register(plate, "plate");
		register(rottenSlabDouble, "rottenSlabDouble", TESBlockSlabBase.SlabItems.RottenSlabDouble.class);
		register(scorchedSlabDouble, "scorchedSlabDouble", TESBlockSlabBase.SlabItems.ScorchedDouble.class);
		register(signCarved, "signCarved");
		register(signCarvedGlowing, "signCarvedGlowing");
		register(skullCup, "skullCup");
		register(slabBoneDouble, "slabBoneDouble", TESBlockSlabBase.SlabItems.BoneDouble.class);
		register(slabClayTileDouble, "slabClayTileDouble", TESBlockSlabBase.SlabItems.ClayTileDouble.class);
		register(slabClayTileDyedDouble1, "slabClayTileDyedDouble1", TESBlockSlabBase.SlabItems.ClayTileDyedDouble.class);
		register(slabClayTileDyedDouble2, "slabClayTileDyedDouble2", TESBlockSlabBase.SlabItems.ClayTileDyed2Double.class);
		register(slabDouble1, "slabDouble1", TESBlockSlabBase.SlabItems.Slab1Double.class);
		register(slabDouble10, "slabDouble10", TESBlockSlabBase.SlabItems.Slab10Double.class);
		register(slabDouble11, "slabDouble11", TESBlockSlabBase.SlabItems.Slab11Double.class);
		register(slabDouble12, "slabDouble12", TESBlockSlabBase.SlabItems.Slab12Double.class);
		register(slabDouble2, "slabDouble2", TESBlockSlabBase.SlabItems.Slab2Double.class);
		register(slabDouble3, "slabDouble3", TESBlockSlabBase.SlabItems.Slab3Double.class);
		register(slabDouble4, "slabDouble4", TESBlockSlabBase.SlabItems.Slab4Double.class);
		register(slabDouble5, "slabDouble5", TESBlockSlabBase.SlabItems.Slab5Double.class);
		register(slabDouble6, "slabDouble6", TESBlockSlabBase.SlabItems.Slab13Double.class);
		register(slabDouble7, "slabDouble7", TESBlockSlabBase.SlabItems.Slab7Double.class);
		register(slabDouble8, "slabDouble8", TESBlockSlabBase.SlabItems.Slab8Double.class);
		register(slabDouble9, "slabDouble9", TESBlockSlabBase.SlabItems.Slab9Double.class);
		register(slabDoubleDirt, "slabDoubleDirt", TESBlockSlabBase.SlabItems.DirtDouble.class);
		register(slabDoubleGravel, "slabDoubleGravel", TESBlockSlabBase.SlabItems.GravelDouble.class);
		register(slabDoubleSand, "slabDoubleSand", TESBlockSlabBase.SlabItems.SandDouble.class);
		register(slabDoubleThatch, "slabDoubleThatch", TESBlockSlabBase.SlabItems.ThatchDouble.class);
		register(slabDoubleV, "slabDoubleV", TESBlockSlabBase.SlabItems.SlabVDouble.class);
		register(sothoryosDoubleTorch, "sothoryosDoubleTorch");
		register(spawnerChest, "spawnerChest");
		register(spawnerChestAncientEssos, "spawnerChestAncientEssos");
		register(spawnerChestStone, "spawnerChestStone");
		register(strawBed, "strawBed");
		register(turnipCrop, "turnip");
		register(wildFire, "wildFire");
		register(wineGlass, "wineGlass");
		register(woodPlate, "woodPlate");
		register(woodSlabDouble1, "woodSlabDouble1", TESBlockSlabBase.SlabItems.WoodSlab1Double.class);
		register(woodSlabDouble2, "woodSlabDouble2", TESBlockSlabBase.SlabItems.WoodSlab2Double.class);
		register(woodSlabDouble3, "woodSlabDouble3", TESBlockSlabBase.SlabItems.WoodSlab3Double.class);
		register(woodSlabDouble4, "woodSlabDouble4", TESBlockSlabBase.SlabItems.WoodSlab4Double.class);
		register(woodSlabDouble5, "woodSlabDouble5", TESBlockSlabBase.SlabItems.WoodSlab5Double.class);
		register(yamCrop, "yam");

		/* redstone */

		register(doorAcacia, "doorAcacia", TESItemDoor.class);
		register(doorBirch, "doorBirch", TESItemDoor.class);
		register(doorDarkOak, "doorDarkOak", TESItemDoor.class);
		register(doorJungle, "doorJungle", TESItemDoor.class);
		register(doorSpruce, "doorSpruce", TESItemDoor.class);
		register(fenceGateAcacia, "fenceGateAcacia");
		register(fenceGateBirch, "fenceGateBirch");
		register(fenceGateDarkOak, "fenceGateDarkOak");
		register(fenceGateJungle, "fenceGateJungle");
		register(fenceGateSpruce, "fenceGateSpruce");
		register(trapdoorAcacia, "trapdoorAcacia");
		register(trapdoorBirch, "trapdoorBirch");
		register(trapdoorDarkOak, "trapdoorDarkOak");
		register(trapdoorJungle, "trapdoorJungle");
		register(trapdoorSpruce, "trapdoorSpruce");

		/* search */

		register(barrier, "barrier");

		/* util */


		register(oven, "oven");
		register(alloyForge, "alloyForge");
		register(unsmeltery, "unsmeltery");
		register(millstone, "millstone");
		register(bank, "bank");
		register(kebabStand, "kebabStand", TESItemKebabStand.class);
		register(kebabStandSand, "kebabStandSand", TESItemKebabStand.class);
		register(beacon, "beacon");
		register(commandTable, "commandTable");

		register(sarbacaneTrap, "sarbacaneTrap");
		register(sarbacaneTrapGold, "sarbacaneTrapGold");
		register(sarbacaneTrapObsidian, "sarbacaneTrapObsidian");

		register(chestBasket, "chestBasket");
		register(chestSandstone, "chestSandstone");
		register(chestStone, "chestStone");

		register(chain, "chain");

		register(doorAlmond, "doorAlmond", TESItemDoor.class);
		register(doorApple, "doorApple", TESItemDoor.class);
		register(doorAramant, "doorAramant", TESItemDoor.class);
		register(doorAspen, "doorAspen", TESItemDoor.class);
		register(doorBanana, "doorBanana", TESItemDoor.class);
		register(doorBaobab, "doorBaobab", TESItemDoor.class);
		register(doorBeech, "doorBeech", TESItemDoor.class);
		register(doorCatalpa, "doorCatalpa", TESItemDoor.class);
		register(doorCedar, "doorCedar", TESItemDoor.class);
		register(doorCharred, "doorCharred", TESItemDoor.class);
		register(doorCherry, "doorCherry", TESItemDoor.class);
		register(doorChestnut, "doorChestnut", TESItemDoor.class);
		register(doorCypress, "doorCypress", TESItemDoor.class);
		register(doorDatePalm, "doorDatePalm", TESItemDoor.class);
		register(doorDragon, "doorDragon", TESItemDoor.class);
		register(doorFir, "doorFir", TESItemDoor.class);
		register(doorFotinia, "doorFotinia", TESItemDoor.class);
		register(doorGreenOak, "doorGreenOak", TESItemDoor.class);
		register(doorHolly, "doorHolly", TESItemDoor.class);
		register(doorIbbinia, "doorIbbinia", TESItemDoor.class);
		register(doorKanuka, "doorKanuka", TESItemDoor.class);
		register(doorLarch, "doorLarch", TESItemDoor.class);
		register(doorLemon, "doorLemon", TESItemDoor.class);
		register(doorLime, "doorLime", TESItemDoor.class);
		register(doorMahogany, "doorMahogany", TESItemDoor.class);
		register(doorMango, "doorMango", TESItemDoor.class);
		register(doorMangrove, "doorMangrove", TESItemDoor.class);
		register(doorMaple, "doorMaple", TESItemDoor.class);
		register(doorOlive, "doorOlive", TESItemDoor.class);
		register(doorOrange, "doorOrange", TESItemDoor.class);
		register(doorPalm, "doorPalm", TESItemDoor.class);
		register(doorPear, "doorPear", TESItemDoor.class);
		register(doorPine, "doorPine", TESItemDoor.class);
		register(doorPlum, "doorPlum", TESItemDoor.class);
		register(doorPomegranate, "doorPomegranate", TESItemDoor.class);
		register(doorRedwood, "doorRedwood", TESItemDoor.class);
		register(doorRotten, "doorRotten", TESItemDoor.class);
		register(doorUlthos, "doorUlthos", TESItemDoor.class);
		register(doorWeirwood, "doorWeirwood", TESItemDoor.class);
		register(doorWillow, "doorWillow", TESItemDoor.class);

		register(fenceGateAlmond, "fenceGateAlmond");
		register(fenceGateApple, "fenceGateApple");
		register(fenceGateAramant, "fenceGateAramant");
		register(fenceGateAspen, "fenceGateAspen");
		register(fenceGateBanana, "fenceGateBanana");
		register(fenceGateBaobab, "fenceGateBaobab");
		register(fenceGateBeech, "fenceGateBeech");
		register(fenceGateCatalpa, "fenceGateCatalpa");
		register(fenceGateCedar, "fenceGateCedar");
		register(fenceGateCharred, "fenceGateCharred");
		register(fenceGateCherry, "fenceGateCherry");
		register(fenceGateChestnut, "fenceGateChestnut");
		register(fenceGateCypress, "fenceGateCypress");
		register(fenceGateDatePalm, "fenceGateDatePalm");
		register(fenceGateDragon, "fenceGateDragon");
		register(fenceGateFir, "fenceGateFir");
		register(fenceGateFotinia, "fenceGateFotinia");
		register(fenceGateGreenOak, "fenceGateGreenOak");
		register(fenceGateHolly, "fenceGateHolly");
		register(fenceGateIbbinia, "fenceGateIbbinia");
		register(fenceGateKanuka, "fenceGateKanuka");
		register(fenceGateLarch, "fenceGateLarch");
		register(fenceGateLemon, "fenceGateLemon");
		register(fenceGateLime, "fenceGateLime");
		register(fenceGateMahogany, "fenceGateMahogany");
		register(fenceGateMango, "fenceGateMango");
		register(fenceGateMangrove, "fenceGateMangrove");
		register(fenceGateMaple, "fenceGateMaple");
		register(fenceGateOlive, "fenceGateOlive");
		register(fenceGateOrange, "fenceGateOrange");
		register(fenceGatePalm, "fenceGatePalm");
		register(fenceGatePear, "fenceGatePear");
		register(fenceGatePine, "fenceGatePine");
		register(fenceGatePlum, "fenceGatePlum");
		register(fenceGatePomegranate, "fenceGatePomegranate");
		register(fenceGateRedwood, "fenceGateRedwood");
		register(fenceGateRotten, "fenceGateRotten");
		register(fenceGateUlthos, "fenceGateUlthos");
		register(fenceGateWeirwood, "fenceGateWeirwood");
		register(fenceGateWillow, "fenceGateWillow");

		register(trapdoorAlmond, "trapdoorAlmond");
		register(trapdoorApple, "trapdoorApple");
		register(trapdoorAramant, "trapdoorAramant");
		register(trapdoorAspen, "trapdoorAspen");
		register(trapdoorBanana, "trapdoorBanana");
		register(trapdoorBaobab, "trapdoorBaobab");
		register(trapdoorBeech, "trapdoorBeech");
		register(trapdoorCatalpa, "trapdoorCatalpa");
		register(trapdoorCedar, "trapdoorCedar");
		register(trapdoorCharred, "trapdoorCharred");
		register(trapdoorCherry, "trapdoorCherry");
		register(trapdoorChestnut, "trapdoorChestnut");
		register(trapdoorCypress, "trapdoorCypress");
		register(trapdoorDatePalm, "trapdoorDatePalm");
		register(trapdoorDragon, "trapdoorDragon");
		register(trapdoorFir, "trapdoorFir");
		register(trapdoorFotinia, "trapdoorFotinia");
		register(trapdoorGreenOak, "trapdoorGreenOak");
		register(trapdoorHolly, "trapdoorHolly");
		register(trapdoorIbbinia, "trapdoorIbbinia");
		register(trapdoorKanuka, "trapdoorKanuka");
		register(trapdoorLarch, "trapdoorLarch");
		register(trapdoorLemon, "trapdoorLemon");
		register(trapdoorLime, "trapdoorLime");
		register(trapdoorMahogany, "trapdoorMahogany");
		register(trapdoorMango, "trapdoorMango");
		register(trapdoorMangrove, "trapdoorMangrove");
		register(trapdoorMaple, "trapdoorMaple");
		register(trapdoorOlive, "trapdoorOlive");
		register(trapdoorOrange, "trapdoorOrange");
		register(trapdoorPalm, "trapdoorPalm");
		register(trapdoorPear, "trapdoorPear");
		register(trapdoorPine, "trapdoorPine");
		register(trapdoorPlum, "trapdoorPlum");
		register(trapdoorPomegranate, "trapdoorPomegranate");
		register(trapdoorRedwood, "trapdoorRedwood");
		register(trapdoorRotten, "trapdoorRotten");
		register(trapdoorUlthos, "trapdoorUlthos");
		register(trapdoorWeirwood, "trapdoorWeirwood");
		register(trapdoorWillow, "trapdoorWillow");

		register(gateEssos, "gateEssos", TESItemGate.class);
		register(gateWesteros, "gateWesteros", TESItemGate.class);
		register(gateIbben, "gateIbben", TESItemGate.class);
		register(gateSothoryos, "gateSothoryos", TESItemGate.class);
		register(gateYiTi, "gateYiTi", TESItemGate.class);

		register(gateBronzeBars, "gateBronzeBars", TESItemGate.class);
		register(gateIronBars, "gateIronBars", TESItemGate.class);

		register(gateWoodenCross, "gateWoodenCross", TESItemGate.class);
		register(gateWooden, "gateWooden", TESItemGate.class);

		register(gateSilver, "gateSilver", TESItemGate.class);
		register(gateGold, "gateGold", TESItemGate.class);
		register(gateValyrian, "gateValyrian", TESItemGate.class);
		
		register(tableEmpire, "tableEmpire");
	}
}