package tes.common.database;

public enum TESGuiId {
	ALLOY_FORGE, ANVIL, ANVIL_NPC, ARMOR_STAND, BARREL, BOOKSHELF, BRANDING_IRON, CHEST, COIN_EXCHANGE, CONQUEST, DISPENSER, EDIT_SIGN, HIRED_FARMER_INVENTORY, HIRED_INTERACT, HIRED_INTERACT_NO_FUNC, HIRED_WARRIOR_INVENTORY, HORN_SELECT, IRON_BANK, MENU, MERCENARY_HIRE, MERCENARY_INTERACT, MILLSTONE, MOUNT_INVENTORY, NPC_RESPAWNER, OVEN, POUCH, POUCH_CHEST, POUCH_MINECART, QUEST_BOOK, SQUADRON_ITEM, TABLE_EMPIRE, TRADE, TRADE_INTERACT, TRADE_UNIT_TRADE_INTERACT, UNIT_TRADE, UNIT_TRADE_INTERACT, UNSMELTERY
}