package tes.common.database;

import tes.common.entity.animal.*;
/*/
import tes.common.entity.essos.TESEntityIfekevron;
import tes.common.entity.essos.TESEntityShryke;
import tes.common.entity.essos.TESEntityStoneMan;
import tes.common.entity.essos.asshai.TESEntityAsshaiShadowbinder;
import tes.common.entity.essos.asshai.TESEntityAsshaiSpherebinder;
import tes.common.entity.essos.asshai.TESEntityAsshaiWarrior;
import tes.common.entity.essos.braavos.TESEntityBraavosLevyman;
import tes.common.entity.essos.braavos.TESEntityBraavosLevymanArcher;
import tes.common.entity.essos.braavos.TESEntityBraavosSoldier;
import tes.common.entity.essos.braavos.TESEntityBraavosSoldierArcher;
import tes.common.entity.essos.ghiscar.*;
import tes.common.entity.essos.gold.TESEntityGoldenSpearman;
import tes.common.entity.essos.gold.TESEntityGoldenWarrior;
import tes.common.entity.essos.ibben.TESEntityIbbenArcher;
import tes.common.entity.essos.ibben.TESEntityIbbenMan;
import tes.common.entity.essos.ibben.TESEntityIbbenWarrior;
import tes.common.entity.essos.jogos.TESEntityJogos;
import tes.common.entity.essos.jogos.TESEntityJogosArcher;
import tes.common.entity.essos.lorath.TESEntityLorathLevyman;
import tes.common.entity.essos.lorath.TESEntityLorathLevymanArcher;
import tes.common.entity.essos.lorath.TESEntityLorathSoldier;
import tes.common.entity.essos.lorath.TESEntityLorathSoldierArcher;
import tes.common.entity.essos.lys.TESEntityLysLevyman;
import tes.common.entity.essos.lys.TESEntityLysLevymanArcher;
import tes.common.entity.essos.lys.TESEntityLysSoldier;
import tes.common.entity.essos.lys.TESEntityLysSoldierArcher;
import tes.common.entity.essos.mossovy.TESEntityMossovyWitcher;
import tes.common.entity.essos.myr.TESEntityMyrLevyman;
import tes.common.entity.essos.myr.TESEntityMyrLevymanArcher;
import tes.common.entity.essos.myr.TESEntityMyrSoldier;
import tes.common.entity.essos.myr.TESEntityMyrSoldierArcher;
import tes.common.entity.essos.norvos.TESEntityNorvosLevyman;
import tes.common.entity.essos.norvos.TESEntityNorvosLevymanArcher;
import tes.common.entity.essos.pentos.TESEntityPentosLevyman;
import tes.common.entity.essos.pentos.TESEntityPentosLevymanArcher;
import tes.common.entity.essos.qarth.TESEntityQarthLevyman;
import tes.common.entity.essos.qarth.TESEntityQarthLevymanArcher;
import tes.common.entity.essos.qohor.TESEntityQohorLevyman;
import tes.common.entity.essos.qohor.TESEntityQohorLevymanArcher;
import tes.common.entity.essos.qohor.TESEntityQohorUnsullied;
import tes.common.entity.essos.tyrosh.TESEntityTyroshLevyman;
import tes.common.entity.essos.tyrosh.TESEntityTyroshLevymanArcher;
import tes.common.entity.essos.tyrosh.TESEntityTyroshSoldier;
import tes.common.entity.essos.tyrosh.TESEntityTyroshSoldierArcher;
import tes.common.entity.essos.volantis.TESEntityVolantisLevyman;
import tes.common.entity.essos.volantis.TESEntityVolantisLevymanArcher;
import tes.common.entity.essos.volantis.TESEntityVolantisSoldier;
import tes.common.entity.essos.volantis.TESEntityVolantisSoldierArcher;
import tes.common.entity.essos.yiti.*;
/*/
import tes.common.entity.other.TESEntityGiantSpider;
import tes.common.entity.other.TESEntityNPC;
import tes.common.entity.other.TESEntityWerewolf;
/*/
import tes.common.entity.sothoryos.sothoryos.TESEntitySothoryosBlowgunner;
import tes.common.entity.sothoryos.sothoryos.TESEntitySothoryosWarrior;
import tes.common.entity.sothoryos.summer.TESEntitySummerArcher;
import tes.common.entity.sothoryos.summer.TESEntitySummerWarrior;
import tes.common.entity.westeros.arryn.*;
import tes.common.entity.westeros.crownlands.TESEntityCrownlandsGuard;
import tes.common.entity.westeros.crownlands.TESEntityCrownlandsLevyman;
import tes.common.entity.westeros.crownlands.TESEntityCrownlandsLevymanArcher;
import tes.common.entity.westeros.crownlands.TESEntityCrownlandsMan;
import tes.common.entity.westeros.dorne.TESEntityDorneLevyman;
import tes.common.entity.westeros.dorne.TESEntityDorneLevymanArcher;
import tes.common.entity.westeros.dorne.TESEntityDorneSoldier;
import tes.common.entity.westeros.dorne.TESEntityDorneSoldierArcher;
import tes.common.entity.westeros.dragonstone.TESEntityDragonstoneLevyman;
import tes.common.entity.westeros.dragonstone.TESEntityDragonstoneLevymanArcher;
import tes.common.entity.westeros.dragonstone.TESEntityDragonstoneSoldier;
import tes.common.entity.westeros.dragonstone.TESEntityDragonstoneSoldierArcher;
import tes.common.entity.westeros.gift.TESEntityGiftGuard;
import tes.common.entity.westeros.hillmen.*;
import tes.common.entity.westeros.ice.TESEntityIceSpider;
import tes.common.entity.westeros.ice.TESEntityWhiteWalker;
import tes.common.entity.westeros.ironborn.TESEntityIronbornLevyman;
import tes.common.entity.westeros.ironborn.TESEntityIronbornLevymanArcher;
import tes.common.entity.westeros.ironborn.TESEntityIronbornSoldier;
import tes.common.entity.westeros.ironborn.TESEntityIronbornSoldierArcher;
import tes.common.entity.westeros.north.*;
import tes.common.entity.westeros.north.hillmen.*;
import tes.common.entity.westeros.reach.*;
import tes.common.entity.westeros.riverlands.TESEntityRiverlandsLevyman;
import tes.common.entity.westeros.riverlands.TESEntityRiverlandsLevymanArcher;
import tes.common.entity.westeros.riverlands.TESEntityRiverlandsSoldier;
import tes.common.entity.westeros.riverlands.TESEntityRiverlandsSoldierArcher;
import tes.common.entity.westeros.stormlands.TESEntityStormlandsLevyman;
import tes.common.entity.westeros.stormlands.TESEntityStormlandsLevymanArcher;
import tes.common.entity.westeros.stormlands.TESEntityStormlandsSoldier;
import tes.common.entity.westeros.stormlands.TESEntityStormlandsSoldierArcher;
import tes.common.entity.westeros.westerlands.*;
import tes.common.entity.westeros.wildling.TESEntityGiant;
import tes.common.entity.westeros.wildling.TESEntityWildling;
import tes.common.entity.westeros.wildling.TESEntityWildlingArcher;
import tes.common.entity.westeros.wildling.thenn.TESEntityThenn;
import tes.common.entity.westeros.wildling.thenn.TESEntityThennArcher;
import tes.common.entity.westeros.wildling.thenn.TESEntityThennBerserker;
/*/
import tes.common.faction.TESFaction;
import tes.common.util.TESReflection;
import tes.common.world.spawning.TESSpawnEntry;
import net.minecraft.util.WeightedRandom;
import net.minecraft.world.World;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class TESSpawnList {

/*/
	public static final TESSpawnList ARRYN_CIVILIAN;
	public static final TESSpawnList ARRYN_CONQUEST;
	public static final TESSpawnList ARRYN_GUARDIAN;
	public static final TESSpawnList ARRYN_MILITARY;
	public static final TESSpawnList ASSHAI_MILITARY;
	public static final TESSpawnList BRAAVOS_CONQUEST;
	public static final TESSpawnList BRAAVOS_MILITARY;
	public static final TESSpawnList CROCODILE;
	public static final TESSpawnList CROWNLANDS_CIVILIAN;
	public static final TESSpawnList CROWNLANDS_GUARDIAN;
	public static final TESSpawnList CROWNLANDS_MILITARY;
	public static final TESSpawnList DESERT_SCORPION;
	public static final TESSpawnList DORNE_CONQUEST;
	public static final TESSpawnList DORNE_MILITARY;
	public static final TESSpawnList DRAGONSTONE_CONQUEST;
	public static final TESSpawnList DRAGONSTONE_MILITARY;
	public static final TESSpawnList GHISCAR_CONQUEST;
	public static final TESSpawnList GHISCAR_GUARDIAN;
	public static final TESSpawnList GHISCAR_HARPY;
	public static final TESSpawnList GHISCAR_MILITARY;
	public static final TESSpawnList GHISCAR_UNSULLIED;
	public static final TESSpawnList GIFT_GUARDIAN;
	public static final TESSpawnList GOLDEN_MILITARY;
	public static final TESSpawnList HILL_TRIBES_CIVILIAN;
	public static final TESSpawnList HILL_TRIBES_MILITARY;
	public static final TESSpawnList IBBEN_CIVILIAN;
	public static final TESSpawnList IBBEN_MILITARY;
	public static final TESSpawnList IFEKEVRON;
	public static final TESSpawnList IRONBORN_CONQUEST;
	public static final TESSpawnList IRONBORN_MILITARY;
	public static final TESSpawnList JOGOS_MILITARY;
	public static final TESSpawnList JUNGLE_SCORPION;
	public static final TESSpawnList LORATH_CONQUEST;
	public static final TESSpawnList LORATH_MILITARY;
	public static final TESSpawnList LYS_CONQUEST;
	public static final TESSpawnList LYS_MILITARY;
	public static final TESSpawnList MANTICORE;
	public static final TESSpawnList MOSSOVY_MILITARY;
	public static final TESSpawnList MOSSOVY_WEREWOLF;
	public static final TESSpawnList MYR_CONQUEST;
	public static final TESSpawnList MYR_MILITARY;
	public static final TESSpawnList NORTH_CIVILIAN;
	public static final TESSpawnList NORTH_CONQUEST;
	public static final TESSpawnList NORTH_GUARDIAN;
	public static final TESSpawnList NORTH_HILLMEN;
	public static final TESSpawnList NORTH_MILITARY;
	public static final TESSpawnList NORVOS_MILITARY;
	public static final TESSpawnList PENTOS_MILITARY;
	public static final TESSpawnList QARTH_MILITARY;
	public static final TESSpawnList QOHOR_MILITARY;
	public static final TESSpawnList REACH_CIVILIAN;
	public static final TESSpawnList REACH_CONQUEST;
	public static final TESSpawnList REACH_GUARDIAN;
	public static final TESSpawnList REACH_MILITARY;
	public static final TESSpawnList RED_SCORPION;
	public static final TESSpawnList RIVERLANDS_CONQUEST;
	public static final TESSpawnList RIVERLANDS_MILITARY;
	public static final TESSpawnList SHRYKE;
	public static final TESSpawnList SOTHORYOS_MILITARY;
	public static final TESSpawnList STORMLANDS_CONQUEST;
	public static final TESSpawnList STORMLANDS_MILITARY;
	public static final TESSpawnList SUMMER_MILITARY;
	public static final TESSpawnList TYROSH_CONQUEST;
	public static final TESSpawnList TYROSH_MILITARY;
	public static final TESSpawnList ULTHOS;
	public static final TESSpawnList VALYRIA;
	public static final TESSpawnList VOLANTIS_CONQUEST;
	public static final TESSpawnList VOLANTIS_MILITARY;
	public static final TESSpawnList WALKERS_CONQUEST;
	public static final TESSpawnList WALKERS_MILITARY;
	public static final TESSpawnList WESTERLANDS_CIVILIAN;
	public static final TESSpawnList WESTERLANDS_CONQUEST;
	public static final TESSpawnList WESTERLANDS_GUARDIAN;
	public static final TESSpawnList WESTERLANDS_MILITARY;
	public static final TESSpawnList WILDING_GIANT;
	public static final TESSpawnList WILDING_MILITARY;
	public static final TESSpawnList WILDING_THENN;
	public static final TESSpawnList WYVERN;
	public static final TESSpawnList YITI_CONQUEST;
	public static final TESSpawnList YITI_MILITARY;

	private static final List<TESSpawnEntry> ARRYN_CIVILIAN_L = new ArrayList<>();
	private static final List<TESSpawnEntry> ARRYN_CONQUEST_L = new ArrayList<>();
	private static final List<TESSpawnEntry> ARRYN_GUARDIAN_L = new ArrayList<>();
	private static final List<TESSpawnEntry> ARRYN_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> ASSHAI_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> BRAAVOS_CONQUEST_L = new ArrayList<>();
	private static final List<TESSpawnEntry> BRAAVOS_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> CROCODILE_L = new ArrayList<>();
	private static final List<TESSpawnEntry> CROWNLANDS_CIVILIAN_L = new ArrayList<>();
	private static final List<TESSpawnEntry> CROWNLANDS_GUARDIAN_L = new ArrayList<>();
	private static final List<TESSpawnEntry> CROWNLANDS_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> DESERT_SCORPION_L = new ArrayList<>();
	private static final List<TESSpawnEntry> DORNE_CONQUEST_L = new ArrayList<>();
	private static final List<TESSpawnEntry> DORNE_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> DRAGONSTONE_CONQUEST_L = new ArrayList<>();
	private static final List<TESSpawnEntry> DRAGONSTONE_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> GHISCAR_CONQUEST_L = new ArrayList<>();
	private static final List<TESSpawnEntry> GHISCAR_GUARDIAN_L = new ArrayList<>();
	private static final List<TESSpawnEntry> GHISCAR_HARPY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> GHISCAR_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> GHISCAR_UNSULLIED_L = new ArrayList<>();
	private static final List<TESSpawnEntry> GIFT_GUARDIAN_L = new ArrayList<>();
	private static final List<TESSpawnEntry> GOLDEN_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> HILL_TRIBES_CIVILIAN_L = new ArrayList<>();
	private static final List<TESSpawnEntry> HILL_TRIBES_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> IBBEN_CIVILIAN_L = new ArrayList<>();
	private static final List<TESSpawnEntry> IBBEN_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> IFEKEVRON_L = new ArrayList<>();
	private static final List<TESSpawnEntry> IRONBORN_CONQUEST_L = new ArrayList<>();
	private static final List<TESSpawnEntry> IRONBORN_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> JOGOS_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> JUNGLE_SCORPION_L = new ArrayList<>();
	private static final List<TESSpawnEntry> LORATH_CONQUEST_L = new ArrayList<>();
	private static final List<TESSpawnEntry> LORATH_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> LYS_CONQUEST_L = new ArrayList<>();
	private static final List<TESSpawnEntry> LYS_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> MANTICORE_L = new ArrayList<>();
	private static final List<TESSpawnEntry> MOSSOVY_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> MOSSOVY_WEREWOLF_L = new ArrayList<>();
	private static final List<TESSpawnEntry> MYR_CONQUEST_L = new ArrayList<>();
	private static final List<TESSpawnEntry> MYR_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> NORTH_CIVILIAN_L = new ArrayList<>();
	private static final List<TESSpawnEntry> NORTH_CONQUEST_L = new ArrayList<>();
	private static final List<TESSpawnEntry> NORTH_GUARDIAN_L = new ArrayList<>();
	private static final List<TESSpawnEntry> NORTH_HILLMEN_L = new ArrayList<>();
	private static final List<TESSpawnEntry> NORTH_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> NORVOS_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> PENTOS_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> QARTH_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> QOHOR_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> REACH_CIVILIAN_L = new ArrayList<>();
	private static final List<TESSpawnEntry> REACH_CONQUEST_L = new ArrayList<>();
	private static final List<TESSpawnEntry> REACH_GUARDIAN_L = new ArrayList<>();
	private static final List<TESSpawnEntry> REACH_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> RED_SCORPION_L = new ArrayList<>();
	private static final List<TESSpawnEntry> RIVERLANDS_CONQUEST_L = new ArrayList<>();
	private static final List<TESSpawnEntry> RIVERLANDS_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> SHRYKE_L = new ArrayList<>();
	private static final List<TESSpawnEntry> SOTHORYOS_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> STORMLANDS_CONQUEST_L = new ArrayList<>();
	private static final List<TESSpawnEntry> STORMLANDS_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> SUMMER_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> TYROSH_CONQUEST_L = new ArrayList<>();
	private static final List<TESSpawnEntry> TYROSH_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> ULTHOS_L = new ArrayList<>();
	private static final List<TESSpawnEntry> VALYRIA_L = new ArrayList<>();
	private static final List<TESSpawnEntry> VOLANTIS_CONQUEST_L = new ArrayList<>();
	private static final List<TESSpawnEntry> VOLANTIS_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> WALKERS_CONQUEST_L = new ArrayList<>();
	private static final List<TESSpawnEntry> WALKERS_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> WESTERLANDS_CIVILIAN_L = new ArrayList<>();
	private static final List<TESSpawnEntry> WESTERLANDS_CONQUEST_L = new ArrayList<>();
	private static final List<TESSpawnEntry> WESTERLANDS_GUARDIAN_L = new ArrayList<>();
	private static final List<TESSpawnEntry> WESTERLANDS_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> WILDING_GIANT_L = new ArrayList<>();
	private static final List<TESSpawnEntry> WILDING_MILITARY_L = new ArrayList<>();
	private static final List<TESSpawnEntry> WILDING_THENN_L = new ArrayList<>();
	private static final List<TESSpawnEntry> WYVERN_L = new ArrayList<>();
	private static final List<TESSpawnEntry> YITI_CONQUEST_L = new ArrayList<>();
	private static final List<TESSpawnEntry> YITI_MILITARY_L = new ArrayList<>();
/*/
	static {
		/*/
		ARRYN_CIVILIAN_L.add(new TESSpawnEntry(TESEntityArrynMan.class, 10, 1, 2));
		ARRYN_CONQUEST_L.add(new TESSpawnEntry(TESEntityArrynSoldier.class, 10, 1, 2));
		ARRYN_CONQUEST_L.add(new TESSpawnEntry(TESEntityArrynSoldierArcher.class, 5, 1, 2));
		ARRYN_GUARDIAN_L.add(new TESSpawnEntry(TESEntityArrynGuard.class, 10, 1, 2));
		ARRYN_MILITARY_L.add(new TESSpawnEntry(TESEntityArrynLevyman.class, 10, 1, 2));
		ARRYN_MILITARY_L.add(new TESSpawnEntry(TESEntityArrynLevymanArcher.class, 5, 1, 2));
		ASSHAI_MILITARY_L.add(new TESSpawnEntry(TESEntityAsshaiShadowbinder.class, 2, 1, 1));
		ASSHAI_MILITARY_L.add(new TESSpawnEntry(TESEntityAsshaiSpherebinder.class, 5, 1, 1));
		ASSHAI_MILITARY_L.add(new TESSpawnEntry(TESEntityAsshaiWarrior.class, 10, 1, 2));
		BRAAVOS_CONQUEST_L.add(new TESSpawnEntry(TESEntityBraavosSoldier.class, 10, 1, 2));
		BRAAVOS_CONQUEST_L.add(new TESSpawnEntry(TESEntityBraavosSoldierArcher.class, 5, 1, 2));
		BRAAVOS_MILITARY_L.add(new TESSpawnEntry(TESEntityBraavosLevyman.class, 10, 1, 2));
		BRAAVOS_MILITARY_L.add(new TESSpawnEntry(TESEntityBraavosLevymanArcher.class, 5, 1, 2));
		CROCODILE_L.add(new TESSpawnEntry(TESEntityCrocodile.class, 10, 1, 1));
		CROWNLANDS_CIVILIAN_L.add(new TESSpawnEntry(TESEntityCrownlandsMan.class, 10, 1, 2));
		CROWNLANDS_GUARDIAN_L.add(new TESSpawnEntry(TESEntityCrownlandsGuard.class, 10, 1, 2));
		CROWNLANDS_MILITARY_L.add(new TESSpawnEntry(TESEntityCrownlandsLevyman.class, 10, 1, 2));
		CROWNLANDS_MILITARY_L.add(new TESSpawnEntry(TESEntityCrownlandsLevymanArcher.class, 5, 1, 2));
		DESERT_SCORPION_L.add(new TESSpawnEntry(TESEntityDesertScorpion.class, 10, 1, 1));
		DORNE_CONQUEST_L.add(new TESSpawnEntry(TESEntityDorneSoldier.class, 10, 1, 2));
		DORNE_CONQUEST_L.add(new TESSpawnEntry(TESEntityDorneSoldierArcher.class, 5, 1, 2));
		DORNE_MILITARY_L.add(new TESSpawnEntry(TESEntityDorneLevyman.class, 10, 1, 2));
		DORNE_MILITARY_L.add(new TESSpawnEntry(TESEntityDorneLevymanArcher.class, 5, 1, 2));
		DRAGONSTONE_CONQUEST_L.add(new TESSpawnEntry(TESEntityDragonstoneSoldier.class, 10, 1, 2));
		DRAGONSTONE_CONQUEST_L.add(new TESSpawnEntry(TESEntityDragonstoneSoldierArcher.class, 5, 1, 2));
		DRAGONSTONE_MILITARY_L.add(new TESSpawnEntry(TESEntityDragonstoneLevyman.class, 10, 1, 2));
		DRAGONSTONE_MILITARY_L.add(new TESSpawnEntry(TESEntityDragonstoneLevymanArcher.class, 5, 1, 2));
		GHISCAR_CONQUEST_L.add(new TESSpawnEntry(TESEntityGhiscarCorsair.class, 10, 1, 2));
		GHISCAR_CONQUEST_L.add(new TESSpawnEntry(TESEntityGhiscarCorsairArcher.class, 5, 1, 2));
		GHISCAR_GUARDIAN_L.add(new TESSpawnEntry(TESEntityGhiscarGuard.class, 10, 1, 2));
		GHISCAR_HARPY_L.add(new TESSpawnEntry(TESEntityGhiscarHarpy.class, 10, 1, 2));
		GHISCAR_MILITARY_L.add(new TESSpawnEntry(TESEntityGhiscarLevyman.class, 10, 1, 2));
		GHISCAR_MILITARY_L.add(new TESSpawnEntry(TESEntityGhiscarLevymanArcher.class, 5, 1, 2));
		GHISCAR_UNSULLIED_L.add(new TESSpawnEntry(TESEntityGhiscarUnsullied.class, 10, 1, 2));
		GIFT_GUARDIAN_L.add(new TESSpawnEntry(TESEntityGiftGuard.class, 10, 1, 2));
		GOLDEN_MILITARY_L.add(new TESSpawnEntry(TESEntityGoldenSpearman.class, 5, 1, 2));
		GOLDEN_MILITARY_L.add(new TESSpawnEntry(TESEntityGoldenWarrior.class, 10, 1, 2));
		HILL_TRIBES_CIVILIAN_L.add(new TESSpawnEntry(TESEntityHillman.class, 10, 1, 2));
		HILL_TRIBES_MILITARY_L.add(new TESSpawnEntry(TESEntityHillmanArcher.class, 5, 1, 2));
		HILL_TRIBES_MILITARY_L.add(new TESSpawnEntry(TESEntityHillmanAxeThrower.class, 3, 1, 2));
		HILL_TRIBES_MILITARY_L.add(new TESSpawnEntry(TESEntityHillmanBerserker.class, 3, 1, 2));
		HILL_TRIBES_MILITARY_L.add(new TESSpawnEntry(TESEntityHillmanWarrior.class, 10, 1, 2));
		IBBEN_CIVILIAN_L.add(new TESSpawnEntry(TESEntityIbbenMan.class, 10, 1, 2));
		IBBEN_MILITARY_L.add(new TESSpawnEntry(TESEntityIbbenArcher.class, 5, 1, 2));
		IBBEN_MILITARY_L.add(new TESSpawnEntry(TESEntityIbbenWarrior.class, 10, 1, 2));
		IFEKEVRON_L.add(new TESSpawnEntry(TESEntityIfekevron.class, 10, 1, 2));
		IRONBORN_CONQUEST_L.add(new TESSpawnEntry(TESEntityIronbornSoldier.class, 10, 1, 2));
		IRONBORN_CONQUEST_L.add(new TESSpawnEntry(TESEntityIronbornSoldierArcher.class, 5, 1, 2));
		IRONBORN_MILITARY_L.add(new TESSpawnEntry(TESEntityIronbornLevyman.class, 10, 1, 2));
		IRONBORN_MILITARY_L.add(new TESSpawnEntry(TESEntityIronbornLevymanArcher.class, 5, 1, 2));
		JOGOS_MILITARY_L.add(new TESSpawnEntry(TESEntityJogos.class, 10, 1, 2));
		JOGOS_MILITARY_L.add(new TESSpawnEntry(TESEntityJogosArcher.class, 5, 1, 2));
		JUNGLE_SCORPION_L.add(new TESSpawnEntry(TESEntityJungleScorpion.class, 10, 1, 1));
		LORATH_CONQUEST_L.add(new TESSpawnEntry(TESEntityLorathSoldier.class, 10, 1, 2));
		LORATH_CONQUEST_L.add(new TESSpawnEntry(TESEntityLorathSoldierArcher.class, 5, 1, 2));
		LORATH_MILITARY_L.add(new TESSpawnEntry(TESEntityLorathLevyman.class, 10, 1, 2));
		LORATH_MILITARY_L.add(new TESSpawnEntry(TESEntityLorathLevymanArcher.class, 5, 1, 2));
		LYS_CONQUEST_L.add(new TESSpawnEntry(TESEntityLysSoldier.class, 10, 1, 2));
		LYS_CONQUEST_L.add(new TESSpawnEntry(TESEntityLysSoldierArcher.class, 5, 1, 2));
		LYS_MILITARY_L.add(new TESSpawnEntry(TESEntityLysLevyman.class, 10, 1, 2));
		LYS_MILITARY_L.add(new TESSpawnEntry(TESEntityLysLevymanArcher.class, 5, 1, 2));
		MANTICORE_L.add(new TESSpawnEntry(TESEntityManticore.class, 10, 1, 1));
		MOSSOVY_MILITARY_L.add(new TESSpawnEntry(TESEntityMossovyWitcher.class, 10, 1, 1));
		MOSSOVY_WEREWOLF_L.add(new TESSpawnEntry(TESEntityWerewolf.class, 10, 1, 2));
		MYR_CONQUEST_L.add(new TESSpawnEntry(TESEntityMyrSoldier.class, 10, 1, 2));
		MYR_CONQUEST_L.add(new TESSpawnEntry(TESEntityMyrSoldierArcher.class, 5, 1, 2));
		MYR_MILITARY_L.add(new TESSpawnEntry(TESEntityMyrLevyman.class, 10, 1, 2));
		MYR_MILITARY_L.add(new TESSpawnEntry(TESEntityMyrLevymanArcher.class, 5, 1, 2));
		NORTH_CIVILIAN_L.add(new TESSpawnEntry(TESEntityNorthMan.class, 10, 1, 2));
		NORTH_CONQUEST_L.add(new TESSpawnEntry(TESEntityNorthSoldier.class, 10, 1, 2));
		NORTH_CONQUEST_L.add(new TESSpawnEntry(TESEntityNorthSoldierArcher.class, 5, 1, 2));
		NORTH_GUARDIAN_L.add(new TESSpawnEntry(TESEntityNorthGuard.class, 10, 1, 2));
		NORTH_HILLMEN_L.add(new TESSpawnEntry(TESEntityNorthHillman.class, 10, 1, 2));
		NORTH_HILLMEN_L.add(new TESSpawnEntry(TESEntityNorthHillmanArcher.class, 5, 1, 2));
		NORTH_HILLMEN_L.add(new TESSpawnEntry(TESEntityNorthHillmanCannibal.class, 5, 1, 2));
		NORTH_HILLMEN_L.add(new TESSpawnEntry(TESEntityNorthHillmanMercenary.class, 5, 1, 2));
		NORTH_HILLMEN_L.add(new TESSpawnEntry(TESEntityNorthHillmanWarrior.class, 5, 1, 2));
		NORTH_MILITARY_L.add(new TESSpawnEntry(TESEntityNorthLevyman.class, 10, 1, 2));
		NORTH_MILITARY_L.add(new TESSpawnEntry(TESEntityNorthLevymanArcher.class, 5, 1, 2));
		NORVOS_MILITARY_L.add(new TESSpawnEntry(TESEntityNorvosLevyman.class, 10, 1, 2));
		NORVOS_MILITARY_L.add(new TESSpawnEntry(TESEntityNorvosLevymanArcher.class, 5, 1, 2));
		PENTOS_MILITARY_L.add(new TESSpawnEntry(TESEntityPentosLevyman.class, 10, 1, 2));
		PENTOS_MILITARY_L.add(new TESSpawnEntry(TESEntityPentosLevymanArcher.class, 5, 1, 2));
		QARTH_MILITARY_L.add(new TESSpawnEntry(TESEntityQarthLevyman.class, 10, 1, 2));
		QARTH_MILITARY_L.add(new TESSpawnEntry(TESEntityQarthLevymanArcher.class, 5, 1, 2));
		QOHOR_MILITARY_L.add(new TESSpawnEntry(TESEntityQohorLevyman.class, 5, 1, 2));
		QOHOR_MILITARY_L.add(new TESSpawnEntry(TESEntityQohorLevymanArcher.class, 2, 1, 2));
		QOHOR_MILITARY_L.add(new TESSpawnEntry(TESEntityQohorUnsullied.class, 10, 1, 2));
		REACH_CIVILIAN_L.add(new TESSpawnEntry(TESEntityReachMan.class, 10, 1, 2));
		REACH_CONQUEST_L.add(new TESSpawnEntry(TESEntityReachSoldier.class, 10, 1, 2));
		REACH_CONQUEST_L.add(new TESSpawnEntry(TESEntityReachSoldierArcher.class, 5, 1, 2));
		REACH_GUARDIAN_L.add(new TESSpawnEntry(TESEntityReachGuard.class, 10, 1, 2));
		REACH_MILITARY_L.add(new TESSpawnEntry(TESEntityReachLevyman.class, 10, 1, 2));
		REACH_MILITARY_L.add(new TESSpawnEntry(TESEntityReachLevymanArcher.class, 5, 1, 2));
		RED_SCORPION_L.add(new TESSpawnEntry(TESEntityRedScorpion.class, 10, 1, 1));
		RIVERLANDS_CONQUEST_L.add(new TESSpawnEntry(TESEntityRiverlandsSoldier.class, 10, 1, 2));
		RIVERLANDS_CONQUEST_L.add(new TESSpawnEntry(TESEntityRiverlandsSoldierArcher.class, 5, 1, 2));
		RIVERLANDS_MILITARY_L.add(new TESSpawnEntry(TESEntityRiverlandsLevyman.class, 10, 1, 2));
		RIVERLANDS_MILITARY_L.add(new TESSpawnEntry(TESEntityRiverlandsLevymanArcher.class, 5, 1, 2));
		SHRYKE_L.add(new TESSpawnEntry(TESEntityShryke.class, 10, 1, 2));
		SOTHORYOS_MILITARY_L.add(new TESSpawnEntry(TESEntitySothoryosBlowgunner.class, 5, 1, 2));
		SOTHORYOS_MILITARY_L.add(new TESSpawnEntry(TESEntitySothoryosWarrior.class, 10, 1, 2));
		STORMLANDS_CONQUEST_L.add(new TESSpawnEntry(TESEntityStormlandsSoldier.class, 10, 1, 2));
		STORMLANDS_CONQUEST_L.add(new TESSpawnEntry(TESEntityStormlandsSoldierArcher.class, 5, 1, 2));
		STORMLANDS_MILITARY_L.add(new TESSpawnEntry(TESEntityStormlandsLevyman.class, 10, 1, 2));
		STORMLANDS_MILITARY_L.add(new TESSpawnEntry(TESEntityStormlandsLevymanArcher.class, 5, 1, 2));
		SUMMER_MILITARY_L.add(new TESSpawnEntry(TESEntitySummerArcher.class, 5, 1, 2));
		SUMMER_MILITARY_L.add(new TESSpawnEntry(TESEntitySummerWarrior.class, 10, 1, 2));
		TYROSH_CONQUEST_L.add(new TESSpawnEntry(TESEntityTyroshSoldier.class, 10, 1, 2));
		TYROSH_CONQUEST_L.add(new TESSpawnEntry(TESEntityTyroshSoldierArcher.class, 5, 1, 2));
		TYROSH_MILITARY_L.add(new TESSpawnEntry(TESEntityTyroshLevyman.class, 10, 1, 2));
		TYROSH_MILITARY_L.add(new TESSpawnEntry(TESEntityTyroshLevymanArcher.class, 5, 1, 2));
		ULTHOS_L.add(new TESSpawnEntry(TESEntityGiantSpider.class, 10, 1, 2));
		VALYRIA_L.add(new TESSpawnEntry(TESEntityStoneMan.class, 10, 1, 2));
		VOLANTIS_CONQUEST_L.add(new TESSpawnEntry(TESEntityVolantisSoldier.class, 10, 1, 2));
		VOLANTIS_CONQUEST_L.add(new TESSpawnEntry(TESEntityVolantisSoldierArcher.class, 5, 1, 2));
		VOLANTIS_MILITARY_L.add(new TESSpawnEntry(TESEntityVolantisLevyman.class, 10, 1, 2));
		VOLANTIS_MILITARY_L.add(new TESSpawnEntry(TESEntityVolantisLevymanArcher.class, 5, 1, 2));
		WALKERS_CONQUEST_L.add(new TESSpawnEntry(TESEntityIceSpider.class, 5, 1, 2));
		WALKERS_CONQUEST_L.add(new TESSpawnEntry(TESEntityWhiteWalker.class, 10, 1, 2));
		WALKERS_MILITARY_L.add(new TESSpawnEntry(TESEntityWhiteWalker.class, 10, 1, 2));
		WESTERLANDS_CIVILIAN_L.add(new TESSpawnEntry(TESEntityWesterlandsMan.class, 10, 1, 2));
		WESTERLANDS_CONQUEST_L.add(new TESSpawnEntry(TESEntityWesterlandsSoldier.class, 10, 1, 2));
		WESTERLANDS_CONQUEST_L.add(new TESSpawnEntry(TESEntityWesterlandsSoldierArcher.class, 5, 1, 2));
		WESTERLANDS_GUARDIAN_L.add(new TESSpawnEntry(TESEntityWesterlandsGuard.class, 10, 1, 2));
		WESTERLANDS_MILITARY_L.add(new TESSpawnEntry(TESEntityWesterlandsLevyman.class, 10, 1, 2));
		WESTERLANDS_MILITARY_L.add(new TESSpawnEntry(TESEntityWesterlandsLevymanArcher.class, 5, 1, 2));
		WILDING_GIANT_L.add(new TESSpawnEntry(TESEntityGiant.class, 10, 1, 1));
		WILDING_MILITARY_L.add(new TESSpawnEntry(TESEntityWildling.class, 10, 1, 2));
		WILDING_MILITARY_L.add(new TESSpawnEntry(TESEntityWildlingArcher.class, 5, 1, 2));
		WILDING_THENN_L.add(new TESSpawnEntry(TESEntityThenn.class, 10, 1, 2));
		WILDING_THENN_L.add(new TESSpawnEntry(TESEntityThennArcher.class, 5, 1, 2));
		WILDING_THENN_L.add(new TESSpawnEntry(TESEntityThennBerserker.class, 10, 1, 2));
		WYVERN_L.add(new TESSpawnEntry(TESEntityWyvern.class, 10, 1, 1));
		YITI_CONQUEST_L.add(new TESSpawnEntry(TESEntityYiTiBombardier.class, 2, 1, 1));
		YITI_CONQUEST_L.add(new TESSpawnEntry(TESEntityYiTiFireThrower.class, 2, 1, 1));
		YITI_CONQUEST_L.add(new TESSpawnEntry(TESEntityYiTiFrontier.class, 10, 1, 2));
		YITI_CONQUEST_L.add(new TESSpawnEntry(TESEntityYiTiFrontierCrossbower.class, 5, 1, 1));
		YITI_CONQUEST_L.add(new TESSpawnEntry(TESEntityYiTiSamurai.class, 2, 1, 2));
		YITI_MILITARY_L.add(new TESSpawnEntry(TESEntityYiTiBombardier.class, 2, 1, 1));
		YITI_MILITARY_L.add(new TESSpawnEntry(TESEntityYiTiFireThrower.class, 2, 1, 1));
		YITI_MILITARY_L.add(new TESSpawnEntry(TESEntityYiTiSoldier.class, 10, 1, 2));
		YITI_MILITARY_L.add(new TESSpawnEntry(TESEntityYiTiSoldierCrossbower.class, 5, 1, 1));
		YITI_MILITARY_L.add(new TESSpawnEntry(TESEntityYiTiSamurai.class, 2, 1, 2));

		ARRYN_CIVILIAN = new TESSpawnList(ARRYN_CIVILIAN_L);
		ARRYN_CONQUEST = new TESSpawnList(ARRYN_CONQUEST_L);
		ARRYN_GUARDIAN = new TESSpawnList(ARRYN_GUARDIAN_L);
		ARRYN_MILITARY = new TESSpawnList(ARRYN_MILITARY_L);
		ASSHAI_MILITARY = new TESSpawnList(ASSHAI_MILITARY_L);
		BRAAVOS_CONQUEST = new TESSpawnList(BRAAVOS_CONQUEST_L);
		BRAAVOS_MILITARY = new TESSpawnList(BRAAVOS_MILITARY_L);
		CROCODILE = new TESSpawnList(CROCODILE_L);
		CROWNLANDS_CIVILIAN = new TESSpawnList(CROWNLANDS_CIVILIAN_L);
		CROWNLANDS_GUARDIAN = new TESSpawnList(CROWNLANDS_GUARDIAN_L);
		CROWNLANDS_MILITARY = new TESSpawnList(CROWNLANDS_MILITARY_L);
		DESERT_SCORPION = new TESSpawnList(DESERT_SCORPION_L);
		DORNE_CONQUEST = new TESSpawnList(DORNE_CONQUEST_L);
		DORNE_MILITARY = new TESSpawnList(DORNE_MILITARY_L);
		DRAGONSTONE_CONQUEST = new TESSpawnList(DRAGONSTONE_CONQUEST_L);
		DRAGONSTONE_MILITARY = new TESSpawnList(DRAGONSTONE_MILITARY_L);
		GHISCAR_CONQUEST = new TESSpawnList(GHISCAR_CONQUEST_L);
		GHISCAR_GUARDIAN = new TESSpawnList(GHISCAR_GUARDIAN_L);
		GHISCAR_HARPY = new TESSpawnList(GHISCAR_HARPY_L);
		GHISCAR_MILITARY = new TESSpawnList(GHISCAR_MILITARY_L);
		GHISCAR_UNSULLIED = new TESSpawnList(GHISCAR_UNSULLIED_L);
		GIFT_GUARDIAN = new TESSpawnList(GIFT_GUARDIAN_L);
		GOLDEN_MILITARY = new TESSpawnList(GOLDEN_MILITARY_L);
		HILL_TRIBES_CIVILIAN = new TESSpawnList(HILL_TRIBES_CIVILIAN_L);
		HILL_TRIBES_MILITARY = new TESSpawnList(HILL_TRIBES_MILITARY_L);
		IBBEN_CIVILIAN = new TESSpawnList(IBBEN_CIVILIAN_L);
		IBBEN_MILITARY = new TESSpawnList(IBBEN_MILITARY_L);
		IFEKEVRON = new TESSpawnList(IFEKEVRON_L);
		IRONBORN_CONQUEST = new TESSpawnList(IRONBORN_CONQUEST_L);
		IRONBORN_MILITARY = new TESSpawnList(IRONBORN_MILITARY_L);
		JOGOS_MILITARY = new TESSpawnList(JOGOS_MILITARY_L);
		JUNGLE_SCORPION = new TESSpawnList(JUNGLE_SCORPION_L);
		LORATH_CONQUEST = new TESSpawnList(LORATH_CONQUEST_L);
		LORATH_MILITARY = new TESSpawnList(LORATH_MILITARY_L);
		LYS_CONQUEST = new TESSpawnList(LYS_CONQUEST_L);
		LYS_MILITARY = new TESSpawnList(LYS_MILITARY_L);
		MANTICORE = new TESSpawnList(MANTICORE_L);
		MOSSOVY_MILITARY = new TESSpawnList(MOSSOVY_MILITARY_L);
		MOSSOVY_WEREWOLF = new TESSpawnList(MOSSOVY_WEREWOLF_L);
		MYR_CONQUEST = new TESSpawnList(MYR_CONQUEST_L);
		MYR_MILITARY = new TESSpawnList(MYR_MILITARY_L);
		NORTH_CIVILIAN = new TESSpawnList(NORTH_CIVILIAN_L);
		NORTH_CONQUEST = new TESSpawnList(NORTH_CONQUEST_L);
		NORTH_GUARDIAN = new TESSpawnList(NORTH_GUARDIAN_L);
		NORTH_HILLMEN = new TESSpawnList(NORTH_HILLMEN_L);
		NORTH_MILITARY = new TESSpawnList(NORTH_MILITARY_L);
		NORVOS_MILITARY = new TESSpawnList(NORVOS_MILITARY_L);
		PENTOS_MILITARY = new TESSpawnList(PENTOS_MILITARY_L);
		QARTH_MILITARY = new TESSpawnList(QARTH_MILITARY_L);
		QOHOR_MILITARY = new TESSpawnList(QOHOR_MILITARY_L);
		REACH_CIVILIAN = new TESSpawnList(REACH_CIVILIAN_L);
		REACH_CONQUEST = new TESSpawnList(REACH_CONQUEST_L);
		REACH_GUARDIAN = new TESSpawnList(REACH_GUARDIAN_L);
		REACH_MILITARY = new TESSpawnList(REACH_MILITARY_L);
		RED_SCORPION = new TESSpawnList(RED_SCORPION_L);
		RIVERLANDS_CONQUEST = new TESSpawnList(RIVERLANDS_CONQUEST_L);
		RIVERLANDS_MILITARY = new TESSpawnList(RIVERLANDS_MILITARY_L);
		SHRYKE = new TESSpawnList(SHRYKE_L);
		SOTHORYOS_MILITARY = new TESSpawnList(SOTHORYOS_MILITARY_L);
		STORMLANDS_CONQUEST = new TESSpawnList(STORMLANDS_CONQUEST_L);
		STORMLANDS_MILITARY = new TESSpawnList(STORMLANDS_MILITARY_L);
		SUMMER_MILITARY = new TESSpawnList(SUMMER_MILITARY_L);
		TYROSH_CONQUEST = new TESSpawnList(TYROSH_CONQUEST_L);
		TYROSH_MILITARY = new TESSpawnList(TYROSH_MILITARY_L);
		ULTHOS = new TESSpawnList(ULTHOS_L);
		VALYRIA = new TESSpawnList(VALYRIA_L);
		VOLANTIS_CONQUEST = new TESSpawnList(VOLANTIS_CONQUEST_L);
		VOLANTIS_MILITARY = new TESSpawnList(VOLANTIS_MILITARY_L);
		WALKERS_CONQUEST = new TESSpawnList(WALKERS_CONQUEST_L);
		WALKERS_MILITARY = new TESSpawnList(WALKERS_MILITARY_L);
		WESTERLANDS_CIVILIAN = new TESSpawnList(WESTERLANDS_CIVILIAN_L);
		WESTERLANDS_CONQUEST = new TESSpawnList(WESTERLANDS_CONQUEST_L);
		WESTERLANDS_GUARDIAN = new TESSpawnList(WESTERLANDS_GUARDIAN_L);
		WESTERLANDS_MILITARY = new TESSpawnList(WESTERLANDS_MILITARY_L);
		WILDING_GIANT = new TESSpawnList(WILDING_GIANT_L);
		WILDING_MILITARY = new TESSpawnList(WILDING_MILITARY_L);
		WILDING_THENN = new TESSpawnList(WILDING_THENN_L);
		WYVERN = new TESSpawnList(WYVERN_L);
		YITI_CONQUEST = new TESSpawnList(YITI_CONQUEST_L);
		YITI_MILITARY = new TESSpawnList(YITI_MILITARY_L);/*/
	}

	private final List<TESSpawnEntry> spawnEntries;

	private TESFaction discoveredFaction;

	@SuppressWarnings("WeakerAccess")
	public TESSpawnList(List<TESSpawnEntry> entries) {
		spawnEntries = entries;
	}

	public TESFaction getListCommonFaction(World world) {
		if (discoveredFaction != null) {
			return discoveredFaction;
		}
		TESFaction commonFaction = null;
		for (TESSpawnEntry entry : spawnEntries) {
			Class<? extends TESEntityNPC> entityClass = entry.entityClass;
			if (TESEntityNPC.class.isAssignableFrom(entityClass)) {
				try {
					TESEntityNPC npc = (TESEntityNPC) TESReflection.newEntity(entityClass, world);
					TESFaction fac = npc.getFaction();
					if (commonFaction == null) {
						commonFaction = fac;
						continue;
					}
					if (commonFaction == fac) {
						continue;
					}
					throw new IllegalArgumentException("Spawn lists must contain only one faction! Mismatched entity class: " + entityClass.getName());
				} catch (Exception e) {
					e.printStackTrace();
					continue;
				}
			}
			throw new IllegalArgumentException("Spawn list must contain only NPCs - invalid " + entityClass.getName());
		}
		if (commonFaction != null) {
			discoveredFaction = commonFaction;
			return discoveredFaction;
		}
		throw new IllegalArgumentException("Failed to discover faction for spawn list");
	}

	public TESSpawnEntry getRandomSpawnEntry(Random rand) {
		return (TESSpawnEntry) WeightedRandom.getRandomItem(rand, spawnEntries);
	}

	public List<TESSpawnEntry> getSpawnEntries() {
		return spawnEntries;
	}
}